#!/bin/sh
. /etc/functions

# generic startup

NFSHOST=fsl00c
NFSBASE=/common/export

log "specific init for $NAME (called by $0)"

[ ! -d /opt/$NAME ] && mkdir -p /opt/$NAME
mount -t nfs -o ro,nolock,nfsvers=2 $NFSHOST:$NFSBASE/timing-rte/b2btest-sis18 /opt/$NAME
/opt/$NAME/$NAME.sh
#umount /opt/$NAME
