// arria10_scu4_lvds_obuf_altera_gpio_181_7mecp6a.v

// This file was auto-generated from altera_gpio_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module arria10_scu4_lvds_obuf_altera_gpio_181_7mecp6a (
		input  wire [0:0] din,       //       din.export
		output wire [0:0] pad_out,   //   pad_out.export
		output wire [0:0] pad_out_b  // pad_out_b.export
	);

	altera_gpio #(
		.SIZE                (1),
		.PIN_TYPE            ("output"),
		.REGISTER_MODE       ("none"),
		.HALF_RATE           ("false"),
		.SEPARATE_I_O_CLOCKS ("false"),
		.BUFFER_TYPE         ("differential"),
		.PSEUDO_DIFF         ("true"),
		.ARESET_MODE         ("none"),
		.SRESET_MODE         ("none"),
		.OPEN_DRAIN          ("false"),
		.BUS_HOLD            ("false"),
		.ENABLE_OE           ("false"),
		.ENABLE_CKE          ("false"),
		.ENABLE_TERM         ("false")
	) core (
		.din                        (din),                  //       din.export
		.pad_out                    (pad_out),              //   pad_out.export
		.pad_out_b                  (pad_out_b),            // pad_out_b.export
		.cke                        (1'b1),                 // (terminated)
		.ck_fr_in                   (1'b0),                 // (terminated)
		.ck_fr_out                  (1'b0),                 // (terminated)
		.ck_in                      (1'b0),                 // (terminated)
		.ck_out                     (1'b0),                 // (terminated)
		.ck_fr                      (1'b0),                 // (terminated)
		.ck                         (1'b0),                 // (terminated)
		.ck_hr_in                   (1'b0),                 // (terminated)
		.ck_hr_out                  (1'b0),                 // (terminated)
		.ck_hr                      (1'b0),                 // (terminated)
		.dout                       (),                     // (terminated)
		.oe                         (1'b0),                 // (terminated)
		.pad_io                     (),                     // (terminated)
		.pad_io_b                   (),                     // (terminated)
		.pad_in                     (1'b0),                 // (terminated)
		.pad_in_b                   (1'b0),                 // (terminated)
		.seriesterminationcontrol   (16'b0000000000000000), // (terminated)
		.parallelterminationcontrol (16'b0000000000000000), // (terminated)
		.aclr                       (1'b0),                 // (terminated)
		.aset                       (1'b0),                 // (terminated)
		.sclr                       (1'b0),                 // (terminated)
		.sset                       (1'b0)                  // (terminated)
	);

endmodule
