MIAN_MODULE := wr_time_test.c

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

CODE_OPTIMIZATION = s

# TOOLCHAIN_DIR = $(INCLUDED_TOOLCHAIN_DIR)

include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================

