TARGET		= pci_control
DEVICE		= 10AX115S2F
FLASH		= EPCQL256
SPI_LANES	= ASx4
RAM_SIZE	= 1073741
SKIP_JIC	= yes
SKIP_CFI	= yes
CFI		= yes
CFI_NAME        = CFI_128Mb
CFI_LANES       = AVSTx32

include ../../build.mk
