onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Wr_Data
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Rd_Data
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Slave_Nr
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Adr
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/SCUB_Addr
add wave -noupdate -radix hexadecimal -childformat {{/scu_addac_vhd_tst/SCUB_Data(15) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(14) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(13) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(12) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(11) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(10) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(9) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(8) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(7) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(6) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(5) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(4) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(3) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(2) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(1) -radix hexadecimal} {/scu_addac_vhd_tst/SCUB_Data(0) -radix hexadecimal}} -subitemconfig {/scu_addac_vhd_tst/SCUB_Data(15) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(14) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(13) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(12) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(11) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(10) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(9) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(8) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(7) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(6) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(5) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(4) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(3) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(2) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(1) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/SCUB_Data(0) {-height 13 -radix hexadecimal}} /scu_addac_vhd_tst/SCUB_Data
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nSCUB_Dtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/scub_wr_fin
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/scub_rd_fin
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nSel_Ext_Data_Drv
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/SCUB_RDnWR
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/scub_wr_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/scub_wr_err_no_dtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/scub_rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/scub_rd_err_no_dtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Timing_In
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/master_clk
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Clk
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Last_Rd_Data
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Start_Cycle
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Wr_Cycle
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Rd_Cycle
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Start_Timing_Cycle
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/SCU_Bus_Access_Active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Intr
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nscub_srq_slaves
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Reset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nscub_timing_cycle
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/scub_ti_cyc_err
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/scub_ti_fin
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Intr_In
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_ADC_DAC_SEL
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_Ext_Data_RD
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/a_ext_io_7_0_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/a_ext_io_15_8_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/a_ext_io_23_16_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/a_ext_io_31_24_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/a_io
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/a_io_7_0_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/a_io_15_8_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/a_io_23_16_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/a_io_31_24_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_nADR_EN
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_nADR_FROM_SCUB
add wave -noupdate -radix hexadecimal -childformat {{/scu_addac_vhd_tst/nSCUB_Slave_Sel(11) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(10) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(9) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(8) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(7) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(6) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(5) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(4) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(3) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(2) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(1) -radix hexadecimal} {/scu_addac_vhd_tst/nSCUB_Slave_Sel(0) -radix hexadecimal}} -subitemconfig {/scu_addac_vhd_tst/nSCUB_Slave_Sel(11) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(10) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(9) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(8) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(7) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(6) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(5) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(4) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(3) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(2) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(1) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/nSCUB_Slave_Sel(0) {-height 13 -radix hexadecimal}} /scu_addac_vhd_tst/nSCUB_Slave_Sel
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nSCUB_DS
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_nEvent_Str
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_nLED
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_nReset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_nSel_Ext_Data_Drv
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_nSRQ
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_nState_LED
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_SEL
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_Spare0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_Spare1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_SysClock
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_TA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_TB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/ADC_BUSY
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/ADC_CONVST_A
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/ADC_CONVST_B
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/ADC_DB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/ADC_FRSTDATA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/ADC_OS
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/ADC_Range
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/ADC_RESET
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/DAC1_SDI
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/DAC2_SDI
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nADC_CS
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nADC_PAR_SER_SEL
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nADC_RD_SCLK
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nDAC1_A0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nDAC1_A1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nDAC1_CLK
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nDAC1_CLR
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nDAC2_A0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nDAC2_A1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nDAC2_CLK
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/nDAC2_CLR
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/scu_master_clk_in_hz
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/master_clk_period
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/slave_clk_in_hz
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/slave_clk_period
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/A_SysClock_period
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Wr
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/Rd
add wave -noupdate -divider {New Divider}
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/CLK_FPGA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_A
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nADR_EN
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nADR_FROM_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_D
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nDS
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_RnW
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nSel_Ext_Data_Drv
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_Ext_Data_RD
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nDtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nSRQ
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nBoardSel
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nEvent_Str
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_SysClock
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_Spare0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_Spare1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nReset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_DB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_CONVST_A
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_CONVST_B
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nADC_CS
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nADC_RD_SCLK
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_BUSY
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_RESET
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_OS
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nADC_PAR_SER_SEL
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_Range
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_FRSTDATA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_ADC_DAC_SEL
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/DAC1_SDI
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nDAC1_CLK
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nDAC1_CLR
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nDAC1_A0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nDAC1_A1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/DAC2_SDI
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nDAC2_CLK
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nDAC2_CLR
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nDAC2_A0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nDAC2_A1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/a_io_7_0_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/a_io_15_8_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/a_io_23_16_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/a_io_31_24_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/a_ext_io_7_0_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/a_ext_io_15_8_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/a_ext_io_23_16_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/a_ext_io_31_24_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/a_io
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_SEL
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_TA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_TB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nState_LED
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/A_nLED
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/clk_sys
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/clk_cal
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/locked
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCUB_SRQ
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCUB_Dtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/convst
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/rst
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/Dtack_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port_Dtack_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port_data_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port_rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac1_Dtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac1_data_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac1_rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac2_Dtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac2_data_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac2_rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADR_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/Data_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/Ext_Adr_Val
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/Ext_Rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/Ext_Wr_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/nPowerup_Res
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/rw_signal
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/led_ena_cnt
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_channel_1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_channel_2
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_channel_3
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_channel_4
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_channel_5
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_channel_6
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_channel_7
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/ADC_channel_8
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/Data_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/modelsim_A_nBoardSel
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/modelsim_nPowerup_Res
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/scu_adda1_id
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/clk_sys_in_Hz
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_spi_clk_in_hz
add wave -noupdate -divider {New Divider}
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/CLK_in_Hz
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Slave_ID
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Firmware_Version
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Firmware_Release
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Hardware_Version
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Hardware_Release
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Intr_Level_Neg
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Intr_Edge_Trig
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Intr_Enable
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/This_macro_vers_dont_change_from_outside
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/This_macro_revi_dont_change_from_outside
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/SCUB_Addr
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/nSCUB_Timing_Cyc
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/SCUB_Data
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/nSCUB_Slave_Sel
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/nSCUB_DS
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/SCUB_RDnWR
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/clk
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/nSCUB_Reset_in
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Data_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Dtack_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Intr_In
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/User_Ready
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Data_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/ADR_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Timing_Pattern_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Timing_Pattern_RCV
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/nSCUB_Dtack_Opdrn
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/SCUB_Dtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/nSCUB_SRQ_Opdrn
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/SCUB_SRQ
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/nSel_Ext_Data_Drv
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Ext_Data_Drv_Rd
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Standard_Reg_Acc
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Ext_Adr_Val
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Ext_Rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Ext_Rd_fin
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Ext_Rd_Fin_ovl
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Ext_Wr_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Ext_Wr_fin
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Ext_Wr_fin_ovl
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Deb_SCUB_Reset_out
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/nPowerup_Res
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_nReset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_ADR_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Adr_Val
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Data_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Timing_Pattern_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Timing_Pat_RCV
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Timing_Pat_RCV_Dly
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_Board_Sel
add wave -noupdate -radix hexadecimal -childformat {{/scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_DS(1) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_DS(0) -radix hexadecimal}} -subitemconfig {/scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_DS(1) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_DS(0) {-height 13 -radix hexadecimal}} /scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_DS
add wave -noupdate -radix hexadecimal -childformat {{/scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_Timing_Cyc(1) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_Timing_Cyc(0) -radix hexadecimal}} -expand -subitemconfig {/scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_Timing_Cyc(1) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_Timing_Cyc(0) {-height 13 -radix hexadecimal}} /scu_addac_vhd_tst/adda1/SCU_Slave/S_nSync_Timing_Cyc
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_DS_Val
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_SCUB_Dtack
add wave -noupdate -radix hexadecimal -childformat {{/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(15) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(14) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(13) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(12) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(11) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(10) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(9) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(8) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(7) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(6) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(5) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(4) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(3) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(2) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(1) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(0) -radix hexadecimal}} -subitemconfig {/scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(15) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(14) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(13) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(12) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(11) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(10) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(9) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(8) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(7) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(6) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(5) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(4) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(3) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(2) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(1) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg(0) {-height 13 -radix hexadecimal}} /scu_addac_vhd_tst/adda1/SCU_Slave/S_Echo_Reg
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Read_Out
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Intr_In_Sync1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Intr_In_Sync2
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Intr_Enable
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Intr_Mask
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Intr_Pending
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Wr_Intr_Pending
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Intr_Active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Wr_Intr_Active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Intr_Level_Neg
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Intr_Edge_Trig
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_SRQ
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Standard_Reg_Acc
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Powerup_Res_Cnt
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Powerup_Res
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Powerup_Done
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Dtack_to_SCUB_Dly
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/S_Deb_Reset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Res
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Clk_in_ps
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/Clk_in_ns
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/C_Powerup_time_in_ns
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/C_Powerup_Res_Cnt
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/C_Powerup_Res_Cnt_len
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/C_Dtack_dly_in_ns
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/C_Dtack_dly_cnt
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/SCU_Slave/C_Debounce_nReset_in_ns
add wave -noupdate -divider {New Divider}
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/Base_addr
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/Adr_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/Data_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/Ext_Adr_Val
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/Ext_Rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/Ext_Wr_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/clk
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/nReset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/io
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/io_7_0_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/ext_io_7_0_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/io_15_8_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/ext_io_15_8_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/io_23_16_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/ext_io_23_16_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/io_31_24_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/ext_io_31_24_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/user_rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/Data_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/Dtack_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/rd_io_15_0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/wr_io_15_0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/rd_io_31_16
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/wr_io_31_16
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/rd_io_7_0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/wr_io_7_0
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/rd_io_15_8
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/wr_io_15_8
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/rd_io_23_16
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/wr_io_23_16
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/rd_io_31_24
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/wr_io_31_24
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/s_dtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/in_15_0_sync1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/in_15_0_sync2
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/in_31_16_sync1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/in_31_16_sync2
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/rd_cntrl_reg
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/wr_cntrl_reg
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/cntrl_reg
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/out_byte1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/out_byte2
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/out_byte3
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/out_byte4
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/s_io_31_24_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/s_io_23_16_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/s_io_15_8_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/s_io_7_0_tx
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/s_ext_io_31_24_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/s_ext_io_23_16_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/s_ext_io_15_8_dis
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/io_port/s_ext_io_7_0_dis
add wave -noupdate -divider {New Divider}
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Base_addr
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/CLK_in_Hz
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/SPI_CLK_in_Hz
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Adr_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Data_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Wr_Shift_Reg
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Ext_Wr_fin
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Dtack
add wave -noupdate -radix hexadecimal -childformat {{/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(15) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(14) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(13) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(12) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(11) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(10) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(9) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(8) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(7) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(6) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(5) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(4) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(3) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(2) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(1) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(0) -radix hexadecimal}} -subitemconfig {/scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(15) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(14) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(13) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(12) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(11) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(10) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(9) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(8) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(7) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(6) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(5) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(4) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(3) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(2) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(1) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg(0) {-height 13 -radix hexadecimal}} /scu_addac_vhd_tst/adda1/dac_1/Shift_Reg
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/spi_clk
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/SPI_TRM
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Ext_Adr_Val
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Ext_Rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Ext_Wr_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/clk
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/nReset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/DAC_SI
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/nDAC_CLK
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/nCS_DAC
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Wr_DAC_Cntrl
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/nLD_DAC
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/nCLR_DAC
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Rd_Port
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Rd_Activ
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/spi_clk_ena
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Rd_DAC_Cntrl
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/S_Dtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/SPI_SM
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/Bit_Cnt
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/S_nCLR_DAC
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/modelsim_nReset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/rw_dac_Cntrl_addr_offset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/wr_dac_addr_offset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/rw_dac_cntrl_addr
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/wr_dac_addr
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/dac_1/c_spi_clk_ena_cnt
add wave -noupdate -divider ADC
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/clk
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/nrst
add wave -noupdate -radix hexadecimal -childformat {{/scu_addac_vhd_tst/adda1/adc/db(13) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(12) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(11) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(10) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(9) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(8) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(7) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(6) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(5) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(4) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(3) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(2) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(1) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/db(0) -radix hexadecimal}} -subitemconfig {/scu_addac_vhd_tst/adda1/adc/db(13) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(12) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(11) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(10) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(9) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(8) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(7) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(6) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(5) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(4) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(3) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(2) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(1) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/db(0) {-height 13 -radix hexadecimal}} /scu_addac_vhd_tst/adda1/adc/db
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/db14_hben
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/db15_byte_sel
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/convst_a
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/convst_b
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/n_cs
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/n_rd_sclk
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/busy
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/adc_reset
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/os
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/par_ser_sel
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/adc_range
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/firstdata
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/Adr_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/Data_from_SCUB_LA
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/Ext_Adr_Val
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/Ext_Rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/Ext_Wr_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/user_rd_active
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/Data_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/Dtack_to_SCUB
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/channel_1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/channel_2
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/channel_3
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/channel_4
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/channel_5
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/channel_6
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/channel_7
add wave -noupdate -radix hexadecimal -childformat {{/scu_addac_vhd_tst/adda1/adc/channel_8(15) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(14) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(13) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(12) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(11) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(10) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(9) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(8) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(7) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(6) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(5) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(4) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(3) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(2) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(1) -radix hexadecimal} {/scu_addac_vhd_tst/adda1/adc/channel_8(0) -radix hexadecimal}} -subitemconfig {/scu_addac_vhd_tst/adda1/adc/channel_8(15) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(14) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(13) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(12) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(11) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(10) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(9) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(8) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(7) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(6) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(5) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(4) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(3) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(2) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(1) {-height 13 -radix hexadecimal} /scu_addac_vhd_tst/adda1/adc/channel_8(0) {-height 13 -radix hexadecimal}} /scu_addac_vhd_tst/adda1/adc/channel_8
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/wr_adc_cntrl
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/rd_adc_cntrl
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/rd_adc_chn_1
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/rd_adc_chn_2
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/rd_adc_chn_3
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/rd_adc_chn_4
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/rd_adc_chn_5
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/rd_adc_chn_6
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/rd_adc_chn_7
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/rd_adc_chn_8
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/dtack
add wave -noupdate -radix hexadecimal /scu_addac_vhd_tst/adda1/adc/adc_cntrl_reg
TreeUpdate [SetDefaultTree]
<<<<<<< HEAD
WaveRestoreCursors {{Cursor 1} {7081420 ps} 0} {{Cursor 2} {9832323 ps} 0} {{Cursor 3} {3220187 ps} 0}
quietly wave cursor active 1
=======
WaveRestoreCursors {{Cursor 1} {6464000 ps} 0} {{Cursor 2} {14448000 ps} 0} {{Cursor 3} {3216000 ps} 0}
>>>>>>> 35a2c9fd63e523cfeba9576440f9acc53697c0d2
configure wave -namecolwidth 175
configure wave -valuecolwidth 81
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
<<<<<<< HEAD
WaveRestoreZoom {0 ps} {10669392 ps}
=======
WaveRestoreZoom {28991288 ps} {29140792 ps}
>>>>>>> 35a2c9fd63e523cfeba9576440f9acc53697c0d2
