

MIAN_MODULE := time_measurement.c

CODE_OPTIMIZATION = s
 # NO_LTO=1
 # TOOLCHAIN_DIR = $(INCLUDED_TOOLCHAIN_DIR)
REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================
