
MIAN_MODULE := eb1test.c

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

LIBS += etherbone

CALL_ARGS = "tcp/$(SCU_URL)"

include $(REPOSITORY_DIR)/makefiles/makefile.scun
#=================================== EOF ======================================

