/********************************************************************************************
 *  b2b-pm.c
 *
 *  created : 2019
 *  author  : Dietrich Beck, GSI-Darmstadt
 *  version : 16-December-2019
 *
 *  firmware required for measuring the h=1 phase for ring machine
 *  
 *  - when receiving B2BTEST_ECADO_PHASEMEAS, the phase is measured as a timestamp for an 
 *    arbitraty period
 *  - the phase timestamp is then sent as a timing message to the network
 *  
 * -------------------------------------------------------------------------------------------
 * License Agreement for this software:
 *
 * Copyright (C) 2018  Dietrich Beck
 * GSI Helmholtzzentrum fuer Schwerionenforschung GmbH
 * Planckstrasse 1
 * D-64291 Darmstadt
 * Germany
 *
 * Contact: d.beck@gsi.de
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *  
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 * For all questions and ideas contact: d.beck@gsi.de
 * Last update: 15-April-2019
 ********************************************************************************************/
#define B2BPM_FW_VERSION 0x000014                                       // make this consistent with makefile

/* standard includes */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdint.h>

/* includes specific for bel_projects */
#include "dbg.h"                                                        // debug outputs
#include "ebm.h"                                                        // EB master
#include "pp-printf.h"                                                  // print
#include "mini_sdb.h"                                                   // sdb stuff
#include "syscon.h"                                                     // usleep et al
#include "aux.h"                                                        // cpu and IRQ
#include "uart.h"                                                       // WR console
#include "stack.h"                                                      // stack check

/* includes for this project */
#include <b2b-common.h>                                                 // common defs for b2b
#include <b2b-test.h>                                                   // specific defs for b2b
#include <b2b-fwlib.h>                                                  // fw library
#include <b2bpm_shared_mmap.h>                                          // autogenerated upon building firmware

// stuff required for environment
extern uint32_t* _startshared[];
unsigned int     cpuId, cpuQty;
#define  SHARED  __attribute__((section(".shared")))
uint64_t SHARED  dummy = 0;

// global variables 
volatile uint32_t *pShared;             // pointer to begin of shared memory region
volatile uint32_t *pSharedTH1ExtHi;     // pointer to a "user defined" u32 register; here: period of h=1 extraction, high bits
volatile uint32_t *pSharedTH1ExtLo;     // pointer to a "user defined" u32 register; here: period of h=1 extraction, low bits
volatile uint32_t *pSharedNHExt;        // pointer to a "user defined" u32 register; here: harmonic number extraction
volatile uint32_t *pSharedTH1InjHi;     // pointer to a "user defined" u32 register; here: period of h=1 injection, high bits
volatile uint32_t *pSharedTH1InjLo;     // pointer to a "user defined" u32 register; here: period of h=1 injecion, low bits
volatile uint32_t *pSharedNHInj;        // pointer to a "user defined" u32 register; here: harmonic number injection

uint32_t *cpuRamExternal;              // external address (seen from host bridge) of this CPU's RAM            

uint64_t statusArray;                   // all status infos are ORed bit-wise into statusArray, statusArray is then published
uint32_t nTransfer;                     // # of transfers
uint32_t transStat;                     // status of transfer, here: meanDelta of 'poor mans fit'

// for phase measurement
#define NSAMPLES 16                     // # of timestamps for sampling h=1
uint64_t tStamp[NSAMPLES];              // timestamp samples

void init() // typical init for lm32
{
  discoverPeriphery();        // mini-sdb ...
  uart_init_hw();             // needed by WR console   
  cpuId = getCpuIdx();

  timer_init(1);              // needed by usleep_init() 
  usleep_init();              // needed for usleep ...
} // init


void initSharedMem(uint32_t *reqState) // determine address and clear shared mem
{
  uint32_t idx;
  uint32_t *pSharedTemp;
  int      i; 
  const uint32_t c_Max_Rams = 10;
  sdb_location found_sdb[c_Max_Rams];
  sdb_location found_clu;
  
  // get pointer to shared memory
  pShared                 = (uint32_t *)_startshared;

  // get address to data
  pSharedTH1ExtHi         = (uint32_t *)(pShared + (B2BTEST_SHARED_TH1EXTHI  >> 2));
  pSharedTH1ExtLo         = (uint32_t *)(pShared + (B2BTEST_SHARED_TH1EXTLO  >> 2));
  pSharedNHExt            = (uint32_t *)(pShared + (B2BTEST_SHARED_NHEXT     >> 2));
  pSharedTH1InjHi         = (uint32_t *)(pShared + (B2BTEST_SHARED_TH1INJHI  >> 2));
  pSharedTH1InjLo         = (uint32_t *)(pShared + (B2BTEST_SHARED_TH1INJLO  >> 2));
  pSharedNHInj            = (uint32_t *)(pShared + (B2BTEST_SHARED_NHINJ     >> 2));
  
  // find address of CPU from external perspective
  idx = 0;
  find_device_multi(&found_clu, &idx, 1, GSI, LM32_CB_CLUSTER);
  if (idx == 0) {
    *reqState = COMMON_STATE_FATAL;
    DBPRINT1("dm-unipz: fatal error - did not find LM32-CB-CLUSTER!\n");
  } // if idx
  idx = 0;
  find_device_multi_in_subtree(&found_clu, &found_sdb[0], &idx, c_Max_Rams, GSI, LM32_RAM_USER);
  if (idx == 0) {
    *reqState = COMMON_STATE_FATAL;
    DBPRINT1("dm-unipz: fatal error - did not find THIS CPU!\n");
  } // if idx
  else cpuRamExternal           = (uint32_t *)(getSdbAdr(&found_sdb[cpuId]) & 0x7FFFFFFF); // CPU sees the 'world' under 0x8..., remove that bit to get host bridge perspective

  DBPRINT2("b2b-pm: CPU RAM External 0x%08x, begin shared 0x%08x\n", (unsigned int)cpuRamExternal, (unsigned int)SHARED_OFFS);

  // clear shared mem
  i = 0;
  pSharedTemp        = (uint32_t *)(pShared + (COMMON_SHARED_BEGIN >> 2 ));
  while (pSharedTemp < (uint32_t *)(pShared + (B2BTEST_SHARED_END >> 2 ))) {
    *pSharedTemp = 0x0;
    pSharedTemp++;
    i++;
  } // while pSharedTemp
  DBPRINT2("b2b-pm: used size of shared mem is %d words (uint32_t), begin %x, end %x\n", i, (unsigned int)pShared, (unsigned int)pSharedTemp-1);

} // initSharedMem 


// clear project specific diagnostics
void extern_clearDiag()
{
  statusArray  = 0x0; 
  nTransfer    = 0;
  transStat    = 0;
} // extern_clearDiag
  

uint32_t extern_entryActionConfigured()
{
  uint32_t status = COMMON_STATUS_OK;

  // disable input gate 
  fwlib_ioCtrlSetGate(0, 2);

  // configure EB master (SRC and DST MAC/IP are set from host)
  if ((status = fwlib_ebmInit(2000, 0xffffffffffff, 0xffffffff, EBM_NOREPLY)) != COMMON_STATUS_OK) {
    DBPRINT1("b2b-pm: ERROR - init of EB master failed! %u\n", (unsigned int)status);
    return status;
  } 

  // get and publish NIC data
  fwlib_publishNICData();

  return status;
} // extern_entryActionConfigured


uint32_t extern_entryActionOperation()
{
  int      i;
  uint64_t tDummy;
  uint64_t eDummy;
  uint64_t pDummy;
  uint32_t fDummy;
  uint32_t flagDummy;

  // clear diagnostics
  fwlib_clearDiag();             

  // flush ECA queue for lm32
  i = 0;
  while (fwlib_wait4ECAEvent(1, &tDummy, &eDummy, &pDummy, &fDummy, &flagDummy) !=  COMMON_ECADO_TIMEOUT) {i++;}
  DBPRINT1("b2b-pm: ECA queue flushed - removed %d pending entries from ECA queue\n", i);

  return COMMON_STATUS_OK;
} // extern_entryActionOperation


uint32_t extern_exitActionOperation()
{
  return COMMON_STATUS_OK;
} // extern_exitActionOperation


uint32_t poorMansFit(uint64_t period, uint32_t nSamples, uint64_t *phase, uint32_t *dt)
{
#define FIRSTTS     2    // index avoid using timestamps with smaller index

  int      i;
  int      usedIdx;      // index of used timestamp
  uint64_t periodNs;     // period in ns
  uint64_t tmp;          // 

  // determine phase
  usedIdx     = nSamples / 2;                                          // use a timestamp in the middle
  if (usedIdx < FIRSTTS)      return B2BTEST_STATUS_PHASEFAILED;       // check range
  if (usedIdx > nSamples -2)  return B2BTEST_STATUS_PHASEFAILED;       // check range, '-2' is on purpose
  *phase      = tStamp[usedIdx];

  // estimate phase error from preceding and successing array element
  // this is tricky, as timestamps are not necessarily ordered
  *dt         = 0;
  periodNs    = (double)period/1000000000.0;                           // convert to ns
  for (i=usedIdx;i<(usedIdx+1); i++) {
    if (tStamp[i] > tStamp[i-1]) tmp = tStamp[i] > tStamp[i-1];
    else                         tmp = tStamp[i-1] > tStamp[i];
    *dt      += tmp % periodNs;                                        // remainder is difference to expected value
  } // for i

  return COMMON_STATUS_OK;
} //poorMansFit


uint32_t doActionOperation(uint64_t *tAct,                    // actual time
                           uint32_t actStatus)                // actual status of firmware
{
  uint32_t status;                                            // status returned by routines
  uint32_t flagIsLate;                                        // flag indicating that we received a 'late' event from ECA
  uint32_t ecaAction;                                         // action triggered by event received from ECA
  uint64_t recDeadline;                                       // deadline received
  uint64_t recEvtId;                                          // evt ID received
  uint64_t recParam;                                          // param received
  uint32_t recTEF;                                            // TEF received
  uint64_t sendDeadline;                                      // deadline to send
  uint64_t sendEvtId;                                         // evtid to send
  uint64_t sendParam;                                         // parameter to send
  
  int      nInput;                                            // # of timestamps
  uint64_t TH1;                                               // h=1 period
  uint64_t tH1Ext;                                            // h=1 timestamp of extraction ( = 'phase')
  uint64_t tH1Inj;                                            // h=1 timestamp of injection ( = 'phase')
  uint32_t dt;                                                // uncertainty of h=1 timestamp

  status = actStatus;

  ecaAction = fwlib_wait4ECAEvent(COMMON_ECATIMEOUT, &recDeadline, &recEvtId, &TH1, &recTEF, &flagIsLate);
   
  switch (ecaAction) {
    case B2BTEST_ECADO_B2B_PMEXT :
      *pSharedTH1ExtHi = (uint32_t)((TH1 >> 32)    & 0xffffffff);
      *pSharedTH1ExtLo = (uint32_t)( TH1           & 0xffffffff);
      *pSharedNHExt    = (uint32_t)( recEvtId      & 0xf       );
      
      nInput = 0;
      fwlib_ioCtrlSetGate(1, 2);                                      // enable input gate
      while (nInput < NSAMPLES) {                                     // treat 1st TS as junk
        ecaAction = fwlib_wait4ECAEvent(100, &recDeadline, &recEvtId, &recParam, &recTEF, &flagIsLate);
        if (ecaAction == B2BTEST_ECADO_TLUINPUT)  {tStamp[nInput] = recDeadline; nInput++;}
        if (ecaAction == B2BTEST_ECADO_TIMEOUT)   break; 
      } // while nInput
      fwlib_ioCtrlSetGate(0, 2);                                      // disable input gate 
      
      DBPRINT2("b2b-pm: extraction phase measurement with samples %d\n", nInput);
      
      if ((nInput == NSAMPLES) && (poorMansFit(TH1, NSAMPLES, &tH1Ext, &dt) == COMMON_STATUS_OK)) {
        // send command: transmit measured phase value
        sendEvtId    = 0x1000000000000000;                                        // FID
        sendEvtId    = sendEvtId | ((uint64_t)B2BTEST_GID << 48);                 // GID chk hackish         
        sendEvtId    = sendEvtId | ((uint64_t)B2BTEST_ECADO_B2B_PREXT << 36);     // EVTNO
        sendParam    = tH1Ext;
        sendDeadline = getSysTime() + COMMON_AHEADT;
        
        fwlib_ebmWriteTM(sendDeadline, sendEvtId, sendParam);

        transStat    = dt;
        
      } // if nInput
      else actStatus = B2BTEST_STATUS_PHASEFAILED;
      
      nTransfer++;
      
      break; // case  B2BTEST_ECADO_B2B_PMEXT
    case B2BTEST_ECADO_B2B_PMINJ :
      *pSharedTH1InjHi = (uint32_t)((TH1 >> 32)    & 0xffffffff);
      *pSharedTH1InjLo = (uint32_t)( TH1           & 0xffffffff);
      *pSharedNHInj    = (uint32_t)( recEvtId      & 0xf       );
      
      nInput = 0;
      fwlib_ioCtrlSetGate(1, 2);                                       // enable input gate
      while (nInput < NSAMPLES) {                                      // treat 1st TS as junk
        ecaAction = fwlib_wait4ECAEvent(100, &recDeadline, &recEvtId, &recParam, &recTEF, &flagIsLate);
        if (ecaAction == B2BTEST_ECADO_TLUINPUT)  {tStamp[nInput] = recDeadline; nInput++;}
        if (ecaAction == B2BTEST_ECADO_TIMEOUT)   break; 
      } // while nInput
      fwlib_ioCtrlSetGate(0, 2);                                      // disable input gate 
      
      DBPRINT2("b2b-pm: injection phase measurement with samples %d\n", nInput);
      
      if ((nInput == NSAMPLES) && (poorMansFit(TH1, NSAMPLES, &tH1Inj, &dt) == COMMON_STATUS_OK)) {
        // send command: transmit measured phase value
        sendEvtId    = 0x1000000000000000;                                        // FID
        sendEvtId    = sendEvtId | ((uint64_t)B2BTEST_GID << 48);                 // GID chk hackish         
        sendEvtId    = sendEvtId | ((uint64_t)B2BTEST_ECADO_B2B_PRINJ << 36);     // EVTNO
        sendParam    = tH1Inj;
        sendDeadline = getSysTime() + COMMON_AHEADT;
        
        fwlib_ebmWriteTM(sendDeadline, sendEvtId, sendParam);

        transStat    = dt;
        
      } // if nInput
      else actStatus = B2BTEST_STATUS_PHASEFAILED;
      
      nTransfer++;
      
      break; // case B2BTEST_ECADO_B2B_PMIN
    default :
      break; // case 'default'
  } // switch ecaAction
 

  status = actStatus; /* chk */
  
  return status;
} // doActionOperation


int main(void) {
  uint64_t tActCycle;                           // time of actual UNILAC cycle
  uint32_t status;                              // (error) status
  uint32_t actState;                            // actual FSM state
  uint32_t pubState;                            // value of published state
  uint32_t reqState;                            // requested FSM state
  uint32_t dummy1;                              // dummy parameter
  uint32_t *buildID;                            // build ID of lm32 firmware
 
  // init local variables
  buildID        = (uint32_t *)(INT_BASE_ADR + BUILDID_OFFS);                 // required for 'stack check'  

  reqState       = COMMON_STATE_S0;
  actState       = COMMON_STATE_UNKNOWN;
  pubState       = COMMON_STATE_UNKNOWN;
  status         = COMMON_STATUS_OK;
  nTransfer      = 0;

  init();                                                                     // initialize stuff for lm32
  initSharedMem(&reqState);                                                   // initialize shared memory
  fwlib_init((uint32_t *)_startshared, cpuRamExternal, SHARED_OFFS, "b2b-pm", B2BPM_FW_VERSION); // init common stuff
  fwlib_clearDiag();                                                          // clear common diagnostics data
  
  while (1) {
    check_stack_fwid(buildID);                                                // check stack status
    fwlib_cmdHandler(&reqState, &dummy1);                                     // check for commands and possibly request state changes
    status = COMMON_STATUS_OK;                                                // reset status for each iteration

    // state machine
    status = fwlib_changeState(&actState, &reqState, status);                 // handle requested state changes
    switch(actState) {                                                        // state specific do actions
      case COMMON_STATE_OPREADY :
        status = doActionOperation(&tActCycle, status);
        if (status == COMMON_STATUS_WRBADSYNC)      reqState = COMMON_STATE_ERROR;
        if (status == COMMON_STATUS_ERROR)          reqState = COMMON_STATE_ERROR;
        break;
      default :                                                               // avoid flooding WB bus with unnecessary activity
        status = fwlib_doActionState(&reqState, actState, status);            // other 'do actions' are handled here
        break;
    } // switch
    
    switch (status) {
      case COMMON_STATUS_OK :                                                 // status OK
        statusArray = statusArray |  (0x1 << COMMON_STATUS_OK);               // set OK bit
        break;
      default :                                                               // status not OK
        if ((statusArray >> COMMON_STATUS_OK) & 0x1) fwlib_incBadStatusCnt(); // changing status from OK to 'not OK': increase 'bad status count'
        statusArray = statusArray & ~((uint64_t)0x1 << COMMON_STATUS_OK);     // clear OK bit
        statusArray = statusArray |  ((uint64_t)0x1 << status);               // set status bit and remember other bits set
        break;
    } // switch status
    
    if ((pubState == COMMON_STATE_OPREADY) && (actState  != COMMON_STATE_OPREADY)) fwlib_incBadStateCnt();
    fwlib_publishStatusArray(statusArray);
    pubState = actState;
    fwlib_publishState(pubState);
    fwlib_publishTransferStatus(nTransfer, 0x0, transStat);
  } // while

  return(1); // this should never happen ...
} // main
