--! @file        prio_auto_pkg.vhd
--  DesignUnit   prio_auto
--! @author      M. Kreider <m.kreider@gsi.de>
--! @date        04/12/2015
--! @version     0.0.1
--! @copyright   2015 GSI Helmholtz Centre for Heavy Ion Research GmbH
--!

--! @brief AUTOGENERATED WISHBONE-SLAVE PACKAGE FOR prio.vhd
--!
--------------------------------------------------------------------------------
--! This library is free software; you can redistribute it and/or
--! modify it under the terms of the GNU Lesser General Public
--! License as published by the Free Software Foundation; either
--! version 3 of the License, or (at your option) any later version.
--!
--! This library is distributed in the hope that it will be useful,
--! but WITHOUT ANY WARRANTY; without even the implied warranty of
--! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
--! Lesser General Public License for more details.
--!
--! You should have received a copy of the GNU Lesser General Public
--! License along with this library. If not, see <http://www.gnu.org/licenses/>.
--------------------------------------------------------------------------------

-- ***********************************************************
-- ** WARNING - THIS IS AUTO-GENERATED CODE! DO NOT MODIFY! **
-- ***********************************************************
--
-- If you want to change the interface,
-- modify prio.xml and re-run 'python wbgenplus.py prio.xml' !

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wishbone_pkg.all;
use work.matrix_pkg.all;
use work.genram_pkg.all;
package prio_auto_pkg is

   constant c_reset_OWR          : natural   := 16#000#; -- wo,          1 b, Resets the Priority Queue
   constant c_mode_GET           : natural   := 16#004#; -- ro,          3 b, b2: Time limit, b1: Msg limit, b0 enable
   constant c_mode_CLR           : natural   := 16#008#; -- wo,          3 b, b2: Time limit, b1: Msg limit, b0 enable
   constant c_mode_SET           : natural   := 16#00c#; -- wo,          3 b, b2: Time limit, b1: Msg limit, b0 enable
   constant c_clear_OWR          : natural   := 16#010#; -- wo,          1 b, Clears counters and status
   constant c_st_full_GET        : natural   := 16#014#; -- ro, g_channels b, Channel Full flag (n..0) 
   constant c_st_late_GET        : natural   := 16#018#; -- ro,          1 b, Late message detected
   constant c_ebm_adr_RW         : natural   := 16#01c#; -- rw,         32 b, Etherbone Master address
   constant c_eca_adr_RW         : natural   := 16#020#; -- rw,         32 b, Event Condition Action Unit address
   constant c_tx_max_msgs_RW     : natural   := 16#024#; -- rw,          8 b, Max msgs per packet
   constant c_tx_max_wait_RW     : natural   := 16#028#; -- rw,         32 b, Max wait time for non empty packet
   constant c_tx_rate_limit_RW   : natural   := 16#02c#; -- rw,         32 b, Max msgs per milliseconds
   constant c_offs_late_RW_0     : natural   := 16#030#; -- rw,         32 b, Time offset before message is late
   constant c_offs_late_RW_1     : natural   := 16#034#; -- rw,         32 b, Time offset before message is late
   constant c_cnt_late_GET       : natural   := 16#038#; -- ro,         32 b, Sum of all late messages
   constant c_ts_late_GET_0      : natural   := 16#03c#; -- ro,         32 b, First late Timestamp
   constant c_ts_late_GET_1      : natural   := 16#040#; -- ro,         32 b, First late Timestamp
   constant c_cnt_out_all_GET_0  : natural   := 16#044#; -- ro,         32 b, Sum of all outgoing messages
   constant c_cnt_out_all_GET_1  : natural   := 16#048#; -- ro,         32 b, Sum of all outgoing messages
   constant c_ch_sel_RW          : natural   := 16#100#; -- rw,          4 b, Channel select
   constant c_cnt_out_GET        : natural   := 16#104#; -- ro,         32 b, Outgoing messages per Channel
   constant c_cnt_in_GET         : natural   := 16#108#; -- ro,         32 b, Incoming messages per Channel

   --| Component ------------------------- prio_auto -------------------------------------------|
   component prio_auto is
   generic(
      g_channels  : natural   := 16 --Input channels
   );
   Port(
      clk_sys_i         : std_logic;                                          -- Clock input for sys domain
      rst_sys_n_i       : std_logic;                                          -- Reset input (active low) for sys domain
      cnt_in_i          : in  matrix(g_channels-1 downto 0, 32-1 downto 0);   -- Incoming messages per Channel
      cnt_late_i        : in  std_logic_vector(32-1 downto 0);                -- Sum of all late messages
      cnt_out_i         : in  matrix(g_channels-1 downto 0, 32-1 downto 0);   -- Outgoing messages per Channel
      cnt_out_all_i     : in  std_logic_vector(64-1 downto 0);                -- Sum of all outgoing messages
      ctrl_stall_i      : in  std_logic_vector(1-1 downto 0);                 -- flow control
      st_full_i         : in  std_logic_vector(g_channels-1 downto 0);        -- Channel Full flag (n..0) 
      st_late_i         : in  std_logic_vector(1-1 downto 0);                 -- Late message detected
      ts_late_i         : in  std_logic_vector(64-1 downto 0);                -- First late Timestamp
      ch_sel_o          : out std_logic_vector(4-1 downto 0);                 -- Channel select
      clear_o           : out std_logic_vector(1-1 downto 0);                 -- Clears counters and status
      ebm_adr_o         : out std_logic_vector(32-1 downto 0);                -- Etherbone Master address
      eca_adr_o         : out std_logic_vector(32-1 downto 0);                -- Event Condition Action Unit address
      mode_o            : out std_logic_vector(3-1 downto 0);                 -- b2: Time limit, b1: Msg limit, b0 enable
      offs_late_o       : out std_logic_vector(64-1 downto 0);                -- Time offset before message is late
      reset_o           : out std_logic_vector(1-1 downto 0);                 -- Resets the Priority Queue
      tx_max_msgs_o     : out std_logic_vector(8-1 downto 0);                 -- Max msgs per packet
      tx_max_wait_o     : out std_logic_vector(32-1 downto 0);                -- Max wait time for non empty packet
      tx_rate_limit_o   : out std_logic_vector(32-1 downto 0);                -- Max msgs per milliseconds
      
      ctrl_i            : in  t_wishbone_slave_in;
      ctrl_o            : out t_wishbone_slave_out

      
   );
   end component;

   constant c_prio_ctrl_sdb : t_sdb_device := (
   abi_class     => x"0000", -- undocumented device
   abi_ver_major => x"01",
   abi_ver_minor => x"00",
   wbd_endian    => c_sdb_endian_big,
   wbd_width     => x"7", -- 8/16/32-bit port granularity
   sdb_component => (
   addr_first    => x"0000000000000000",
   addr_last     => x"00000000000001ff",
   product => (
   vendor_id     => x"0000000000000651",
   device_id     => x"10040200",
   version       => x"00000001",
   date          => x"20151204",
   name          => "DM-PriorityQ-Ctrl  ")));

end prio_auto_pkg;
package body prio_auto_pkg is
end prio_auto_pkg;
