/********************************************************************************************
 *  wr-mil.c
 *
 *  created : 2024
 *  author  : Dietrich Beck, Micheal Reese, Mathias Kreider GSI-Darmstadt
 *  version : 08-feb-2024
 *
 *  firmware required for the White Rabbit -> MIL Gateways
 *  
 *  This firmware is a refactured fork of the original 'wr-mil-gw' developed for SIS18 and ESR
 *  by Michael Reese and others. The fork was triggered by the need of a wr-mil-gateway at UNILAC. 
 *  
 * -------------------------------------------------------------------------------------------
 * License Agreement for this software:
 *
 * Copyright (C) 2018  Dietrich Beck
 * GSI Helmholtzzentrum fuer Schwerionenforschung GmbH
 * Planckstrasse 1
 * D-64291 Darmstadt
 * Germany
 *
 * Contact: d.beck@gsi.de
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either

 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *  
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *
 * For all questions and ideas contact: d.beck@gsi.de
 * Last update: 15-April-2019
 ********************************************************************************************/
#define WRMIL_FW_VERSION      0x000001    // make this consistent with makefile

#define MILSEND_LATENCY        25000      // nanoseconds from pushing to mil piggy/sio queue to last transition on the mil bus
#define MICROSECONDS           1000       // so many nanoseconds per microsecond
#define RESET_INHIBIT_COUNTER  1000       // count so many main loops before the inhibit for fill event sending is released
#define N_UTC_EVENTS           5          // number of generated EVT_UTC events
#define ECA_QUEUE_LM32_TAG     0x00000004 // the tag for ECA actions we (the LM32) want to receive
#define WR_MIL_GATEWAY_LATENCY 70650      // additional latency in units of nanoseconds
                                          // this value was determined by measuring the time difference
                                          // of the MIL event rising edge and the ECA output rising edge (no offset)
                                          // and tuning this time difference to 100.0(5)us


// standard includes
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdint.h>

// includes specific for bel_projects
#include "dbg.h"                                                        // debug outputs
#include <stack.h>                                                      // stack check
#include "pp-printf.h"                                                  // print
#include "mini_sdb.h"                                                   // sdb stuff
#include "aux.h"                                                        // cpu and IRQ
#include "uart.h"                                                       // WR console
#include "../../../top/gsi_scu/scu_mil.h"                               // register layout of 'MIL macro'

// includes for this project 
#include <common-defs.h>                                                // common defs for firmware
#include <common-fwlib.h>                                               // common routines for firmware
#include <wr-mil.h>                                                     // specific defs for wr-mil
#include <wrmil_shared_mmap.h>                                          // autogenerated upon building firmware

// stuff required for environment
extern uint32_t* _startshared[];
unsigned int     cpuId, cpuQty;
#define  SHARED  __attribute__((section(".shared")))
uint64_t SHARED  dummy = 0;

// global variables 
volatile uint32_t *pShared;                // pointer to begin of shared memory region
volatile uint32_t *pSharedSetUtcTrigger;   // pointer to a "user defined" u32 register; here: the MIL event that triggers the generation of UTC events
volatile uint32_t *pSharedSetUtcUtcDelay;  // pointer to a "user defined" u32 register; here: delay [us] between the 5 generated UTC MIL events
volatile uint32_t *pSharedSetTrigUtcDelay; // pointer to a "user defined" u32 register; here: delay [us] between the trigger event and the first UTC (and other) generated events
volatile uint32_t *pSharedSetGid;          // pointer to a "user defined" u32 register; here: GID the gateway will be using
volatile uint32_t *pSharedSetLatency;      // pointer to a "user defined" u32 register; here: MIL event is generated xxx us+latency after the WR event. The value of latency can be negative
volatile uint32_t *pSharedSetUtcOffsHi;    // pointer to a "user defined" u32 register; here: delay [ms] between the TAI and the MIL-UTC, high word
volatile uint32_t *pSharedSetUtcOffsLo;    // pointer to a "user defined" u32 register; here: delay [ms] between the TAI and the MIL-UTC, low word
volatile uint32_t *pSharedSetReqFillEvt;   // pointer to a "user defined" u32 register; here: if this is written to 1, the gateway will send a fill event as soon as possible
volatile uint32_t *pSharedSetMilDev;       // pointer to a "user defined" u32 register; here: MIL device for sending MIL messages; 0: MIL Piggy; 1..: SIO in slot 1..
volatile uint32_t *pSharedSetMilMon;       // pointer to a "user defined" u32 register; here: 1: monitor MIL events; 0; don't monitor MIL events
volatile uint32_t *pSharedGetNEvtsHi;      // pointer to a "user defined" u32 register; here: number of translated events, high word
volatile uint32_t *pSharedGetNEvtsLo;      // pointer to a "user defined" u32 register; here: number of translated events, high word
volatile uint32_t *pSharedGetNLateEvts;    // pointer to a "user defined" u32 register; here: number of late events
volatile uint32_t *pSharedGetComLatency;   // pointer to a "user defined" u32 register; here: communicatin latency for events received by ECA
//volatile uint32_t *pSharedGetNLateHisto;   // pointer to a "user defined" u32 register; here: dummy register to indicate position after the last valid register
//volatile uint32_t *pSharedGetNMilHisto;    // pointer to a "user defined" u32 register; here: dummy register to indicate position after the last valid register
//volatile uint32_t *pSharedGetMsiSlot;      // pointer to a "user defined" u32 register; here: MSI slot is stored here


uint32_t *cpuRamExternal;               // external address (seen from host bridge) of this CPU's RAM
volatile uint32_t *pMilSend;            // address of MIL device sending timing messages, usually this will be a SIO
volatile uint32_t *pMilRec;             // address of MIL device receiving timing messages, usually this will be a MIL piggy

uint64_t statusArray;                   // all status infos are ORed bit-wise into statusArray, statusArray is then published
uint64_t nMessages;                     // # of sent messages
int32_t  comLatency;                    // latency for messages received via ECA

uint32_t utc_trigger;
int32_t  utc_utc_delay;
int32_t  trig_utc_delay;
uint64_t utc_offset;
uint32_t mil_latency;
uint32_t mil_domain;

// debug 
uint64_t t1, t2;
int32_t  tmp1;

void init() // typical init for lm32
{
  discoverPeriphery();        // mini-sdb ...
  uart_init_hw();             // needed by WR console   
  cpuId = getCpuIdx();
} // init


// determine address and clear shared mem
void initSharedMem(uint32_t *reqState, uint32_t *sharedSize)
{
  uint32_t idx;
  uint32_t *pSharedTemp;
  int      i; 
  const uint32_t c_Max_Rams = 10;
  sdb_location   found_sdb[c_Max_Rams];
  sdb_location   found_clu;
  
  // get pointer to shared memory
  pShared                    = (uint32_t *)_startshared;

  // get address to data
  pSharedSetUtcTrigger       = (uint32_t *)(pShared + (WRMIL_SHARED_SET_UTC_TRIGGER       >> 2));
  pSharedSetUtcUtcDelay      = (uint32_t *)(pShared + (WRMIL_SHARED_SET_UTC_UTC_DELAY     >> 2));
  pSharedSetTrigUtcDelay     = (uint32_t *)(pShared + (WRMIL_SHARED_SET_TRIG_UTC_DELAY    >> 2));
  pSharedSetGid              = (uint32_t *)(pShared + (WRMIL_SHARED_SET_GID               >> 2));
  pSharedSetLatency          = (uint32_t *)(pShared + (WRMIL_SHARED_SET_LATENCY           >> 2));
  pSharedSetUtcOffsHi        = (uint32_t *)(pShared + (WRMIL_SHARED_SET_UTC_OFFSET_HI     >> 2));
  pSharedSetUtcOffsLo        = (uint32_t *)(pShared + (WRMIL_SHARED_SET_UTC_OFFSET_LO     >> 2));
  pSharedSetReqFillEvt       = (uint32_t *)(pShared + (WRMIL_SHARED_SET_REQUEST_FILL_EVT  >> 2));
  pSharedSetMilDev           = (uint32_t *)(pShared + (WRMIL_SHARED_SET_MIL_DEV           >> 2));
  pSharedSetMilMon           = (uint32_t *)(pShared + (WRMIL_SHARED_SET_MIL_MON           >> 2));
  pSharedGetNEvtsHi          = (uint32_t *)(pShared + (WRMIL_SHARED_GET_NUM_EVENTS_HI     >> 2));
  pSharedGetNEvtsLo          = (uint32_t *)(pShared + (WRMIL_SHARED_GET_NUM_EVENTS_LO     >> 2));
  pSharedGetNLateEvts        = (uint32_t *)(pShared + (WRMIL_SHARED_GET_LATE_EVENTS       >> 2));
  pSharedGetComLatency       = (uint32_t *)(pShared + (WRMIL_SHARED_GET_COM_LATENCY       >> 2));
  //pSharedGetNLateHisto       = (uint32_t *)(pShared + (WRMIL_SHARED_GET_LATE_HISTOGRAM    >> 2));
  //pSharedGetNMilHisto        = (uint32_t *)(pShared + (WRMIL_SHARED_GET_MIL_HISTOGRAM     >> 2));
  //pSharedGetMsiSlot          = (uint32_t *)(pShared + (WRMIL_SHARED_GET_MSI_SLOT          >> 2));

  // find address of CPU from external perspective
  idx = 0;
  find_device_multi(&found_clu, &idx, 1, GSI, LM32_CB_CLUSTER);
  if (idx == 0) {
    *reqState = COMMON_STATE_FATAL;
    DBPRINT1("wr-mil: fatal error - did not find LM32-CB-CLUSTER!\n");
  } // if idx
  idx = 0;
  find_device_multi_in_subtree(&found_clu, &found_sdb[0], &idx, c_Max_Rams, GSI, LM32_RAM_USER);
  if (idx == 0) {
    *reqState = COMMON_STATE_FATAL;
    DBPRINT1("wr-mil: fatal error - did not find THIS CPU!\n");
  } // if idx
  else cpuRamExternal = (uint32_t *)(getSdbAdr(&found_sdb[cpuId]) & 0x7FFFFFFF); // CPU sees the 'world' under 0x8..., remove that bit to get host bridge perspective

  DBPRINT2("wr-mil: CPU RAM external 0x%8x, shared offset 0x%08x\n", cpuRamExternal, SHARED_OFFS);
  DBPRINT2("wr-mil: fw common shared begin   0x%08x\n", pShared);
  DBPRINT2("wr-mil: fw common shared end     0x%08x\n", pShared + (COMMON_SHARED_END >> 2));

  // clear shared mem
  i = 0;
  pSharedTemp        = (uint32_t *)(pShared + (COMMON_SHARED_END >> 2 ) + 1);
  DBPRINT2("wr-mil: fw specific shared begin 0x%08x\n", pSharedTemp);
  while (pSharedTemp < (uint32_t *)(pShared + (WRMIL_SHARED_END >> 2 ))) {
    *pSharedTemp = 0x0;
    pSharedTemp++;
    i++;
  } // while pSharedTemp
  DBPRINT2("wr-mil: fw specific shared end   0x%08x\n", pSharedTemp);

  *sharedSize        = (uint32_t)(pSharedTemp - pShared) << 2;

  // basic info to wr console
  DBPRINT1("\n");
  DBPRINT1("wr-mil: initSharedMem, shared size [bytes]: %d\n", *sharedSize);
  DBPRINT1("\n");
} // initSharedMem 


// clear project specific diagnostics
void extern_clearDiag()
{
} // extern_clearDiag
  

// entry action 'configured' state
uint32_t extern_entryActionConfigured()
{
  uint32_t status = COMMON_STATUS_OK;

  // get and publish NIC data
  fwlib_publishNICData(); 

  // get address of MIL device sending MIL telegrams; 0 is MIL piggy
  if (*pSharedSetMilDev == 0){
    pMilSend = fwlib_getMilPiggy();
    if (!pMilSend) return COMMON_STATUS_OUTOFRANGE;
  } // if SetMilDev
  else {
    // SCU slaves have offsets 0x20000, 0x40000... for slots 1, 2 ...
    pMilSend = fwlib_getSbMaster();
    if (!pMilSend) return COMMON_STATUS_OUTOFRANGE;
    else pMilSend += *pSharedSetMilDev * 0x20000;
  } // else SetMilDev

  // reset MIL sender and wait
  if ((status = resetPiggyDevMil(pMilSend))  != MIL_STAT_OK) {
    DBPRINT1("wr-mil: ERROR - can't reset MIL device; sender\n");
    return WRMIL_STATUS_MIL;
  }  // if reset

  // get address of MIL device receiving MIL telegrams; only piggy is supported
  if (*pSharedSetMilMon){
    pMilRec = fwlib_getMilPiggy();
    if (!pMilRec) return COMMON_STATUS_OUTOFRANGE;
  } // if SetMilMon
  
  // reset MIL receiver and wait
  if ((status = resetPiggyDevMil(pMilRec))  != MIL_STAT_OK) {
    DBPRINT1("wr-mil: ERROR - can't reset MIL device; receiver\n");
    return WRMIL_STATUS_MIL;
  }  // if reset

  return status;
} // extern_entryActionConfigured


// entry action 'operation' state
uint32_t extern_entryActionOperation()
{
  int      i;
  uint64_t tDummy;
  uint64_t eDummy;
  uint64_t pDummy;
  uint32_t fDummy;
  uint32_t flagDummy1, flagDummy2, flagDummy3, flagDummy4;

  // clear diagnostics
  fwlib_clearDiag();             

  // flush ECA queue for lm32
  i = 0;
  while (fwlib_wait4ECAEvent(1000, &tDummy, &eDummy, &pDummy, &fDummy, &flagDummy1, &flagDummy2, &flagDummy3, &flagDummy4) !=  COMMON_ECADO_TIMEOUT) {i++;}
  DBPRINT1("wr-mil: ECA queue flushed - removed %d pending entries from ECA queue\n", i);
  // init set values
    
  // init get values
  *pSharedGetNEvtsHi        = 0x0;
  *pSharedGetNEvtsLo        = 0x0;
  *pSharedGetNLateEvts      = 0x0;
  *pSharedGetComLatency     = 0x0;
  //*pSharedGetNLateHisto     = 0x0;
  //*pSharedGetNMilHisto      = 0x0; 
  //*pSharedGetMsiSlot        = 0x0;

  // int set values
  utc_trigger    = *pSharedSetUtcTrigger;
  utc_utc_delay  = *pSharedSetUtcUtcDelay;
  trig_utc_delay = *pSharedSetTrigUtcDelay;
  utc_offset     = (uint64_t)(*pSharedSetUtcOffsHi) << 32;
  utc_offset    |= (uint64_t)(*pSharedSetUtcOffsLo);
  mil_latency    = *pSharedSetLatency;
  mil_domain     = *pSharedSetGid;

  return COMMON_STATUS_OK;
} // extern_entryActionOperation


uint32_t extern_exitActionOperation()
{
  return COMMON_STATUS_OK;
} // extern_exitActionOperation


// conversion of WR timing message from Data Master to MIL telegram; original code from wr-mil-gw (Michael Reese, Peter Kainberger)
// note that the mapping has been changed
uint32_t convert_WReventID_to_milTelegram(uint64_t evtId, uint32_t *milTelegram)
{
  // EventID 
  // |---------------evtIdHi---------------|  |---------------evtIdLo---------------|
  // FFFF GGGG GGGG GGGG EEEE EEEE EEEE FFFF  SSSS SSSS SSSS BBBB BBBB BBBB BBRR RRRR
  //                          cccc cccc irrr  ssss ssss vvvv
  //                                               xxxx xxxx
  //                              
  // F: FID(4)
  // G: GID(12)
  // E: EVTNO(12) = evtNo
  // F: FLAGS(4)
  // S: SID(12)
  // B: BPID(14)
  // R: Reserved(10)
  // s: status bits
  // v: virtAcc = virtual accellerator
  // c: evtCode = MIL relevant part of the evtNo (only 0..255)
  // i: InBeam(1)
  // r: reserved(3)
  // x: other content for special events like (code=200..208 command events)
  //    or (code=200 beam status event) 

  uint32_t evtNo;                         // 12 bit evtNo of WR message
  uint32_t evtCode;
  uint32_t tophalf;                       // the top half bits (15..8) of the mil telegram; the meaning depends on the evtCode.
  uint32_t virtAcc;                       // # of virtual accelerator
  uint32_t statusBits;                    // top bits (12..15) the the mil telegram
  uint32_t pzKennung;                     // for beamtime only (SIS18, ESR)
  uint32_t gid;                           // group ID, WR message

  evtNo      = (evtId >> 36)       & 0x00000fff;       // 12 bits
  evtCode    = evtNo               & 0x000000ff;       // mil telegram is limited to 0..255
  statusBits = evtId               & 0x0000000f;       // lower 4 bits of evtIdReserved
  virtAcc    = (evtId >> 20)       & 0x0000000f;       // lower 4 bits of SID
  gid        = (evtId >> 48)       & 0x00000fff;       // GID

  tophalf    = statusBits << 4;
  tophalf   |= virtAcc;

  // legacy code for the 2024 beam time - or maybe a special case for ring machines
  if ((gid == SIS18_RING || gid == ESR_RING)) {
    switch (gid) {
      case SIS18_RING: pzKennung = 0x1; break;
      case ESR_RING:   pzKennung = 0x2; break;
      default :        pzKennung = 0x0; break;
    } // switch gid
    
    // commands: top half of the MIL bits (15..8) are extracted from the status bits of EventID
    if (evtCode >= 200 && evtCode <= 208) {
      // tophalf = tophalf;  // no modification (just take all bits from the sequence-ID)
    } // if evtCode
    else if (evtCode == 255) { // command event: top half of the MIL bits (15..8) are pppp1111, p is pzKennung
    tophalf = ( pzKennung << 4 ) | 0xf;          
    } // evtCode 255
    else {                                // all other events: top half of MIL bits (15..8) are ppppvvvv, p is pzKennung
      tophalf = ( pzKennung << 4 ) | virtAcc;
    } // else evtCode 255
  } // if ring machine

  *milTelegram = (tophalf << 8) | evtCode; 
                                           
  // For MIL events, the upper 4 bits ov evtNo are zero
  return (evtNo & 0x00000f00) == 0; 
} // convert_WReventID_to_milTelegram


// do action of state operation: This is THE central code of this firmware
uint32_t doActionOperation(uint64_t *tAct,                    // actual time
                           uint32_t actStatus)                // actual status of firmware
{
  uint32_t status;                                            // status returned by routines
  uint32_t flagIsLate;                                        // flag indicating that we received a 'late' event from ECA
  uint32_t flagIsEarly;                                       // flag 'early'
  uint32_t flagIsConflict;                                    // flag 'conflict'
  uint32_t flagIsDelayed;                                     // flag 'delayed'
  uint32_t ecaAction;                                         // action triggered by event received from ECA
  uint64_t recDeadline;                                       // deadline received from ECA
  uint64_t reqDeadline;                                       // deadline requested by sender
  uint64_t recEvtId;                                          // evt ID received
  uint64_t recParam;                                          // param received
  uint32_t recTEF;                                            // TEF received
  uint32_t recGid;                                            // GID received
  uint32_t recSid;                                            // SID received
  uint32_t recBpid;                                           // BPID received
  uint64_t sendDeadline;                                      // deadline to send
  uint64_t sendEvtId;                                         // evtid to send
  uint64_t sendParam;                                         // parameter to send
  uint32_t sendTEF;                                           // TEF to send
  static uint64_t previous_time = 0;                          // protect for nonsense high frequency bursts
  uint32_t milTelegram;                                       // telegram to be sent
  
  status    = actStatus;

  ecaAction = fwlib_wait4ECAEvent(COMMON_ECATIMEOUT * 1000, &recDeadline, &recEvtId, &recParam, &recTEF, &flagIsLate, &flagIsEarly, &flagIsConflict, &flagIsDelayed);

  switch (ecaAction) {
    // the following two cases handle h=1 group DDS phase measurement
    case WRMIL_ECADO_MIL_EVT:
      comLatency    = (int32_t)(getSysTime() - recDeadline);
      convert_WReventID_to_milTelegram(recEvtId, &milTelegram);

      // build timing message and inject into ECA

      // deadline
      sendDeadline  = recDeadline + mil_latency * MICROSECONDS - MILSEND_LATENCY;
      // protect from nonsense hi-frequency bursts
      if (sendDeadline < previous_time + MILSEND_LATENCY) sendDeadline = previous_time + MILSEND_LATENCY;
      previous_time = sendDeadline;

      // evtID
      sendEvtId     = recEvtId;
      sendEvtId    |= (uint64_t)0xfff << 48;  // overwrite GID with 0xfff to signal for local message

      // param
      sendParam     = (uint64_t)milTelegram & 0xffffffff;
      fwlib_ecaWriteTM(sendDeadline, sendEvtId, sendParam, 0x0, 0);
      
      break; 
     
    default :                                                         // flush ECA queue
      flagIsLate = 0;                                                 // ingore late events
  } // switch ecaAction
 
  // check for late event
  if ((status == COMMON_STATUS_OK) && flagIsLate) status = WRMIL_STATUS_LATEMESSAGE;
  
  // check WR sync state
  if (fwlib_wrCheckSyncState() == COMMON_STATUS_WRBADSYNC) return COMMON_STATUS_WRBADSYNC;
  else                                                     return status;
} // doActionOperation


int main(void) {
  uint64_t tActMessage;                         // time of actual message
  uint32_t status;                              // (error) status
  uint32_t actState;                            // actual FSM state
  uint32_t pubState;                            // value of published state
  uint32_t reqState;                            // requested FSM state
  uint32_t dummy1;                              // dummy parameter
  uint32_t sharedSize;                          // size of shared memory
  uint32_t *buildID;                            // build ID of lm32 firmware

  // init local variables
  buildID        = (uint32_t *)(INT_BASE_ADR + BUILDID_OFFS);                 // required for 'stack check'  

  reqState       = COMMON_STATE_S0;
  actState       = COMMON_STATE_UNKNOWN;
  pubState       = COMMON_STATE_UNKNOWN;
  status         = COMMON_STATUS_OK;
  nMessages      = 0;

  init();                                                                     // initialize stuff for lm32
  initSharedMem(&reqState, &sharedSize);                                      // initialize shared memory
  fwlib_init((uint32_t *)_startshared, cpuRamExternal, SHARED_OFFS, sharedSize, "wr-mil", WRMIL_FW_VERSION); // init common stuff
  fwlib_clearDiag();                                                          // clear common diagnostics data
  
  while (1) {
    check_stack_fwid(buildID);                                                // check stack status
    fwlib_cmdHandler(&reqState, &dummy1);                                     // check for commands and possibly request state changes
    status = COMMON_STATUS_OK;                                                // reset status for each iteration

    // state machine
    status = fwlib_changeState(&actState, &reqState, status);                 // handle requested state changes
    switch(actState) {                                                        // state specific do actions
      case COMMON_STATE_OPREADY :
        status = doActionOperation(&tActMessage, status);
        if (status == COMMON_STATUS_WRBADSYNC)      reqState = COMMON_STATE_ERROR;
        if (status == COMMON_STATUS_ERROR)          reqState = COMMON_STATE_ERROR;
        break;
      default :                                                               // avoid flooding WB bus with unnecessary activity
        status = fwlib_doActionState(&reqState, actState, status);            // other 'do actions' are handled here
        break;
    } // switch
    
    switch (status) {
      case COMMON_STATUS_OK :                                                 // status OK
        statusArray = statusArray |  (0x1 << COMMON_STATUS_OK);               // set OK bit
        break;
      default :                                                               // status not OK
        if ((statusArray >> COMMON_STATUS_OK) & 0x1) fwlib_incBadStatusCnt(); // changing status from OK to 'not OK': increase 'bad status count'
        statusArray = statusArray & ~((uint64_t)0x1 << COMMON_STATUS_OK);     // clear OK bit
        statusArray = statusArray |  ((uint64_t)0x1 << status);               // set status bit and remember other bits set
        break;
    } // switch status
    
    if ((pubState == COMMON_STATE_OPREADY) && (actState  != COMMON_STATE_OPREADY)) fwlib_incBadStateCnt();
    fwlib_publishStatusArray(statusArray);
    pubState = actState;
    fwlib_publishState(pubState);
    *pSharedGetComLatency = comLatency;
  } // while

  return(1); // this should never happen ...
} // main
