testcase = TestCase(
  "Test_Basic_Run_all_CPUs",
  [ Op("Init0_0", "cmd", "halt"),
    Op("Init0_1", "sched", "clear"),
    Op("Init0_2", "sched", "add", "0", "test_sched.dot"),
    Op("Test0_0_CheckNone", "sched", "rawvisited", "0.0", None, "test0_0_exp.txt"),
    Op("Test0_1_RunCPU0", "cmd", "startpattern IN_C0"),
    Op("Test0_2_CheckCPU0", "sched", "rawvisited", "0.1", None, "test0_2_exp.txt"),
    Op("Init1_0", "cmd", "halt"),
    Op("Init1_1", "sched", "clear"),
    Op("Init1_2", "sched", "add", "0", "test_sched.dot"),
    Op("Test1_0_CheckNone", "sched", "rawvisited", "0.0", None, "test0_0_exp.txt"),
    Op("Test1_1_RunCPU1", "cmd", "startpattern IN_C1"),
    Op("Test1_2_CheckCPU1", "sched", "rawvisited", "0.1", None, "test1_2_exp.txt"),
    Op("Init2_0", "cmd", "halt"),
    Op("Init2_1", "sched", "clear"),
    Op("Init2_2", "sched", "add", "0", "test_sched.dot"),
    Op("Test2_0_CheckNone", "sched", "rawvisited", "0.0", None, "test0_0_exp.txt"),
    Op("Test2_1_RunCPU2", "cmd", "startpattern IN_C2"),
    Op("Test2_2_CheckCPU2", "sched", "rawvisited", "0.1", None, "test2_2_exp.txt"),
    Op("Init3_0", "cmd", "halt"),
    Op("Init3_1", "sched", "clear"),
    Op("Init3_2", "sched", "add", "0", "test_sched.dot"),
    Op("Test3_0_CheckNone", "sched", "rawvisited", "0.0", None, "test0_0_exp.txt"),
    Op("Test3_1_RunCPU3", "cmd", "startpattern IN_C3"),
    Op("Test3_2_CheckCPU3", "sched", "rawvisited", "0.1", None, "test3_2_exp.txt"),
  ]
)