

MIAN_MODULE := helloworld.c


SYN_DIR = ../../../

INCLUDE_DIRS = ./
INCLUDE_DIRS += ../../../top/gsi_scu


include $(SYN_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================
