/*!
 *  @file daq_eb_ram_buffer.cpp
 *  @brief Linux whishbone/etherbone interface for accessing the SCU-DDR3 RAM
 *
 *  @see scu_ramBuffer.h
 *
 *  @see scu_ddr3.h
 *  @see scu_ddr3.c
 *  @date 19.06.2019
 *  @copyright (C) 2019 GSI Helmholtz Centre for Heavy Ion Research GmbH
 *
 *  @author Ulrich Becker <u.becker@gsi.de>
 *
 *******************************************************************************
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 3 of the License, or (at your option) any later version.
 *
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library. If not, see <http://www.gnu.org/licenses/>.
 *******************************************************************************
 */
#include <daq_eb_ram_buffer.hpp>
#include <generated/shared_mmap.h>
#include <dbg.h>
#include <iostream>
using namespace Scu;
using namespace daq;

///////////////////////////////////////////////////////////////////////////////
/*! ---------------------------------------------------------------------------
 * @see daq_eb_ram_buffer.hpp
 */
EbRamAccess::EbRamAccess( DaqEb::EtherboneConnection* poEb )
   :m_poEb( poEb )
   ,m_connectedBySelf( false )
#ifndef CONFIG_NO_SCU_RAM
  #ifdef CONFIG_SCU_USE_DDR3
   ,m_ddr3TrModeBase( 0 )
   #ifndef CONFIG_DDR3_NO_BURST_FUNCTIONS
   ,m_ddr3BurstModeBase( 0 )
   #endif
  #endif
#endif
#ifdef CONFIG_EB_TIME_MEASSUREMENT
   , m_startTime( 0 )
   , m_minElapsedTime( static_cast<USEC_T>(~0) )
   , m_maxElapsedTime( 0 )
#endif
{
   if( !m_poEb->isConnected() )
   {
      m_poEb->connect();
      m_connectedBySelf = true;
   }

   m_lm32SharedMemAddr = m_poEb->findDeviceBaseAddress( DaqEb::gsiId,
                                                        DaqEb::lm32_ram_user );
   /*
    * NOTE: The constant SHARED_OFFS is defined in generated/shared_mmap.h.
    * The file shared_mmap.h becomes generated by the makefile which builds the
    * LM32 binary.
    */
   m_lm32SharedMemAddr += SHARED_OFFS;

#ifndef CONFIG_NO_SCU_RAM
 #ifdef CONFIG_SCU_USE_DDR3
   m_ddr3TrModeBase = m_poEb->findDeviceBaseAddress( DaqEb::gsiId, DaqEb::wb_ddr3ram );
  #ifndef CONFIG_DDR3_NO_BURST_FUNCTIONS
   m_ddr3BurstModeBase = m_poEb->findDeviceBaseAddress( DaqEb::gsiId, DaqEb::wb_ddr3ram2 );
  #endif
 #endif
#endif

}

/*! ---------------------------------------------------------------------------
 * @see daq_eb_ram_buffer.hpp
 */
EbRamAccess::~EbRamAccess( void )
{
   if( m_connectedBySelf )
      m_poEb->disconnect();
}

#ifndef CONFIG_NO_SCU_RAM
/*! ---------------------------------------------------------------------------
 * @see daq_eb_ram_buffer.hpp
 */
void EbRamAccess::readRam( RAM_DAQ_PAYLOAD_T* pData, std::size_t len,
                           RAM_RING_INDEXES_T& rIndexes
                        #ifndef CONFIG_DDR3_NO_BURST_FUNCTIONS
                           , RAM_DAQ_POLL_FT poll
                        #endif
                         )
{
 #if defined( CONFIG_DDR3_NO_BURST_FUNCTIONS )
   RAM_RING_INDEXES_T indexes = rIndexes;
   const std::size_t lenToEnd = ramRingGetUpperReadSize( &indexes );
   if( lenToEnd < len )
   {
      readRam( pData, lenToEnd, ramRingGetReadIndex( &indexes ) );
      ramRingAddToReadIndex( &indexes, lenToEnd );
      len   -= lenToEnd;
      pData += lenToEnd;
   }
   readRam( pData, len, ramRingGetReadIndex( &indexes ) );
   ramRingAddToReadIndex( &indexes, len );
   rIndexes = indexes;
 #else
   #warning At the moment the burst mode is slow!
   RAM_RING_INDEXES_T indexes = rIndexes;
   const uint = lenToEnd = ramRingGetUpperReadSize( &indexes );
   if( lenToEnd < len )
   {
      //TODO
      ret = ddr3FlushFiFo( ramRingGeReadIndex( &indexes ),
                           lenToEnd, pData, poll );
      if( ret != EB_OK )
         return ret;
      ramRingAddToReadIndex( &indexes, lenToEnd );
      len   -= lenToEnd;
      pData += lenToEnd;
   }
   //TODO
   ret = ddr3FlushFiFo( ramRingGeReadIndex( &indexes ),
                        len, pData, poll );
   if( ret != EB_OK )
      return ret;
   ramRingAddToReadIndex( &indexes, len );
   rIndexes = indexes;
 #endif
}
#endif /* #ifndef CONFIG_NO_SCU_RAM */

#ifdef CONFIG_EB_TIME_MEASSUREMENT
#warning "Timemeasurment output to stderr is active"
/*! ---------------------------------------------------------------------------
 * @see daq_eb_ram_buffer.hpp
 */
void EbRamAccess::stopTimeMeasurement( void )
{
   const USEC_T newDuration = getSysMicrosecs() - m_startTime;
   if( newDuration > m_maxElapsedTime )
   {
      std::cerr << "WB max duration: " << newDuration << " us" << std::endl;
      m_maxElapsedTime = newDuration;
   }
   if( newDuration < m_minElapsedTime )
   {
      std::cerr << "WB min duration: " << newDuration << " us" << std::endl;
      m_minElapsedTime = newDuration;
   }
}
#endif

//================================== EOF =======================================
