

MIAN_MODULE := ../helloworld.c

CODE_OPTIMIZATION = 2

REPOSITORY_DIR = $(shell git rev-parse --show-toplevel)
DEPLOY_DIR  ?= ../deploy_$(CPU)
TARGET_URL_FILE = $(HOME)/scu.url

include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================
