C_SOURCES += \
  main.c \
  $(NEORV32_SRC_FILES_DIR)neorv32_uart.c \
  $(NEORV32_SRC_FILES_DIR)neorv32_aux.c \
  $(NEORV32_SRC_FILES_DIR)neorv32_cpu.c \
  $(NEORV32_SRC_FILES_DIR)neorv32_rte.c \
  $(NEORV32_SRC_FILES_DIR)neorv32_gpio.c \
  $(NEORV32_COMMON_DIR)gsi_test_neorv32.c

include ../common/Makefile.common
