files = [ 
  "aux_functions_pkg.vhd",
  "Debounce.vhd",
  "div_n.vhd",
  "led_n.vhd",
  "lemo_io.vhd",
  "tmr_scu_bus.vhd",
  "sys_clk_or_local_clk.vhd",
  "IO_4x8.vhd",
  "Zeitbasis.vhd",
  "slave_clk_switch.vhd",
  "local_20_to_12p5.vhd",
  "local_125_to_12p5.vhd",
  "prio_encoder/prio_encoder_16_4.vhd",
  "prio_encoder/prio_encoder_64_6.vhd",
  "prio_encoder/prio_encoder_256_8.vhd",
  "in_reg.vhd",
  "io_reg.vhd"
]
