// arria10_scu4_lvds_obuf.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module arria10_scu4_lvds_obuf (
		input  wire [0:0] din,       //       din.export
		output wire [0:0] pad_out,   //   pad_out.export
		output wire [0:0] pad_out_b  // pad_out_b.export
	);

	arria10_scu4_lvds_obuf_altera_gpio_181_7mecp6a gpio_0 (
		.din       (din),       //       din.export
		.pad_out   (pad_out),   //   pad_out.export
		.pad_out_b (pad_out_b)  // pad_out_b.export
	);

endmodule
