files = [ "VME64xCore_Top.vhd",
          "vme64x_pack.vhd",
          "VME_Access_Decode.vhd",
          "VME_Am_Match.vhd",
          "VME_bus.vhd",
          "VME_CR_CSR_Space.vhd",
          "VME_CR_pack.vhd",
          "VME_CSR_pack.vhd",
          "VME_CRAM.vhd",
          "VME_Funct_Match.vhd",
          "VME_Init.vhd",
          "VME_IRQ_Controller.vhd",
          "VME_SharedComps.vhd",
          "VME_swapper.vhd",
          "VME_Wb_master.vhd"]
