
MIAN_MODULE := irq_test.c

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

include $(REPOSITORY_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================
