
MIAN_MODULE := irq_test.c

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================
