
MIAN_MODULE := irq_test.c


SYN_DIR = ../../../

TARGET_URL_FILE = $(HOME)/scu.url

include $(SYN_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================
