
MIAN_MODULE := cpptest.cpp

SYN_DIR = ../../../

SCU_DIR = $(SYN_DIR)top/gsi_scu

INCLUDE_DIRS = ./
INCLUDE_DIRS += $(SCU_DIR)

SOURCE += $(SCU_DIR)/dow_crc.c


TARGET_URL_FILE = $(HOME)/scu.url

include $(SYN_DIR)/modules/lm32_makefiles/makefile.scu


