MIAN_MODULE := static_test.c

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

CODE_OPTIMIZATION = s

# TOOLCHAIN_DIR = $(REPOSITORY_DIR)/toolchain/bin/

include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================

