MIAN_MODULE := static_test.c

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

CODE_OPTIMIZATION = 2

include $(REPOSITORY_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================

