MIAN_MODULE := static_test.c

SYN_DIR = ../../../

SCU_DIR = $(SYN_DIR)top/gsi_scu

INCLUDE_DIRS = ./
INCLUDE_DIRS += $(SCU_DIR)

TARGET_URL_FILE = ~/target.url

include $(SYN_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================


