#!/bin/bash

_get_eb_dev() 
{
	local dm_devlist
	dm_devlist=`history | cut -c 8- | grep -v "grep" | grep "\(eb\-\)[a-zA-Z0-9\-\_]*" | grep -o -E "(dev|tcp|udp)\/.[a-zA-Z0-9\_\-\.]*"`

	echo $dm_devlist
}
 _eb_tools() 
{
    

    local cur prev dm_devlist
  	COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    

    if [ $COMP_CWORD -eq 1 ]; then
    	dm_devlist=$(_get_eb_dev);
    	COMPREPLY=( $(compgen -W "${dm_devlist}" -- $cur) )
   	fi

    return 0
   
}

 _eb_flash() 
{
    local cur prev dm_devlist
  	COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    
    if [ $COMP_CWORD -eq 1 ]; then
    	dm_devlist=$(_get_eb_dev)
    	COMPREPLY=( $(compgen -W "${dm_devlist}" -- $cur) )
		elif [ $COMP_CWORD -eq 2 ]; then
    	COMPREPLY=( $( compgen -f -X '!*.rpd' -- $cur ) )
   	fi

    return 0
   
}

 _eb_flash() 
{
		_get_eb_dev    

    local cur prev dm_devlist
  	COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    
    if [ $COMP_CWORD -eq 1 ]; then
    	dm_devlist=$(_get_eb_dev)
    	COMPREPLY=( $(compgen -W "${dm_devlist}" -- $cur) )
		elif [ $COMP_CWORD -eq 2 ]; then
    	COMPREPLY=()
    elif [ $COMP_CWORD -eq 3 ]; then
   		COMPREPLY=( $(compgen -W "0" -- $cur) )
   	elif [ $COMP_CWORD -eq 4 ]; then
   		COMPREPLY=( $( compgen -f -X '!*.bin' -- $cur ) )
   	fi

    return 0
   
}

complete -F _eb_tools eb-ls
complete -F _eb_tools eb-info
complete -F _eb_tools eb-console
complete -F _eb_tools eb-mon
complete -F _eb_tools eb-reset

complete -o filenames -F _eb_flash eb_flash
complete -o filenames -F _eb_flash eb_flash

