MIAN_MODULE := shared.c

SYN_DIR = ../../../

TARGET_URL_FILE = $(HOME)/target.url


SHARED_SIZE     = 12

SOURCE += $(SCU_LIB_SRC_DIR)/shared_memory_helper.c
SOURCE += $(SCU_LIB_SRC_DIR)/aux.c
SOURCE += $(SCU_LIB_SRC_DIR)/irq.c

include $(SYN_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================


