set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TX_CLK]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD0]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD1]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TX_CTL]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD0] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD2]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD3]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_MDIO] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_MDIO]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_MDC]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RX_CTL] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RX_CLK] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD2] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD3] -to *
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO0]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO1]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO2]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO3]
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_SS0]
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_CMD] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CMD]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D1]
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D1]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D4] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D4]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D5] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D5]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D6] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D6]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D7] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D7]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_CLK] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_STP]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_DIR] -to *
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_NXT] -to *
set_false_path -from [get_ports hps_io_hps_io_uart0_inst_RX] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_uart0_inst_TX]
set_false_path -from [get_ports hps_io_hps_io_uart1_inst_RX] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_uart1_inst_TX]
set_false_path -from [get_ports hps_io_hps_io_i2c0_inst_SDA] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c0_inst_SDA]
set_false_path -from [get_ports hps_io_hps_io_i2c0_inst_SCL] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c0_inst_SCL]
set_false_path -from * -to [get_ports hps_io_hps_io_trace_inst_CLK]
set_false_path -from * -to [get_ports hps_io_hps_io_trace_inst_D0]
set_false_path -from * -to [get_ports hps_io_hps_io_trace_inst_D1]
set_false_path -from * -to [get_ports hps_io_hps_io_trace_inst_D2]
set_false_path -from * -to [get_ports hps_io_hps_io_trace_inst_D3]
set_false_path -from * -to [get_ports hps_io_hps_io_trace_inst_D4]
set_false_path -from * -to [get_ports hps_io_hps_io_trace_inst_D5]
set_false_path -from * -to [get_ports hps_io_hps_io_trace_inst_D6]
set_false_path -from * -to [get_ports hps_io_hps_io_trace_inst_D7]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO00] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO00]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO17] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO17]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO18] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO18]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO22] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO22]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO24] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO24]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO26] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO26]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO27] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO27]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO35] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO35]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO40] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO40]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO41] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO41]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO42] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO42]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO43] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO43]