

MIAN_MODULE := ../helloworld.c

CODE_OPTIMIZATION = 2

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)
DEPLOY_DIR  ?= ../deploy_$(CPU)

include $(REPOSITORY_DIR)/modules/lm32_makefiles/makefile.scun
#=================================== EOF ======================================
