

MIAN_MODULE := ../helloworld.c

CODE_OPTIMIZATION = 2

SYN_DIR = ../../../..
DEPLOY_DIR  ?= ../deploy_$(CPU)

include $(SYN_DIR)/modules/lm32_makefiles/makefile.scun
#=================================== EOF ======================================
