

MIAN_MODULE := assert_test.c


SYN_DIR = ../../../

#DEFINES = CONFIG_LM32_ASSERT_CONTINUE

include $(SYN_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================
