

MIAN_MODULE := assert_test.c


REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

# DEFINES = CONFIG_SCU_ASSERT_CONTINUE
# DEFINES += CONFIG_SCU_ASSERT_NO_COLORED
include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================
