

MIAN_MODULE := assert_test.c


REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

#DEFINES = CONFIG_LM32_ASSERT_CONTINUE

include $(REPOSITORY_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================
