#!/bin/bash

# Plausibility check
if (( $# != 2 )); then
  echo "Error: Illegal number of parameters ($# given, 2 expected)"
  echo "Example usage: $0 dev/wbmX gateware.rpd"
  exit 1
fi

# Get arguments
v_device="$1"
v_gateware="$2"

if [ ! -f "$v_gateware" ]; then
  echo "Error: Gateware '$v_gateware' not found!"
  exit 1
fi

# Check if saftbusd is running
if ps -ax | grep -v grep | grep -q "saftbusd"; then
  echo "Warning: saftbusd is currently running!"
fi

# Disable watchdog timer
eb-reset "$v_device" wddisable
if [ $? -ne 0 ]; then
  echo "Error: Failed to disable the watchdog timer!"
  exit 2
fi

# Stop all embedded CPUs
eb-reset "$v_device" cpuhalt 0xff
if [ $? -ne 0 ]; then
  echo "Error: Failed to halt all CPUs!"
  exit 3
fi

# Flash device
eb-flash "$v_device" "$v_gateware"
if [ $? -ne 0 ]; then
  echo "Error: Failed to flash the device!"
  exit 4
fi

# Done
echo "Flash successful! Consider to run eb-reset $v_device fpgareset to restart the FPGA."
