#! /bin/sh

dev="$1"
set -ex

eca-ctl $dev enable
eca-ctl $dev idisable
eca-ctl $dev activate -c 2

eca-table $dev flush
eca-table $dev add 0xdeadbeef/64 0 2 0x000fff
eca-table $dev add 0xdeadbeef/64 4 2 0xfff000
eca-table $dev flip-active

period=125000000
while true; do
 sleep 1
 when=`eca-ctl $dev -n | grep time | cut -d: -f2`
 eca-ctl $dev send 0xdeadbeef 0 0 $(((when+period+pediod-1)/period*period))
done
