MIAN_MODULE := scu_bus_test.c

SYN_DIR = ../../../

SOURCE += $(SCU_DIR)/scu_bus.c
SOURCE += $(SCU_DIR)/dow_crc.c
SOURCE += $(WR_DIR)/dev/w1-temp.c

DEFINES += CONFIG_SCU_BUS_PEDANTIC_CHECK

include $(SYN_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================

