#!/usr/bin/env bash

# A script which clones the diob2-planning repo int blackbox/

# Local directory
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"



 git clone https://git.gsi.de/hel-public/blackbox $SCRIPT_DIR/blackbox
