#!/usr/bin/env bash

# Local directory
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"


# Default value
DEFAULT_CONFIGURATION="default"

# Use the first argument if provided, otherwise default
CONFIGURATION="${1:-$DEFAULT_CONFIGURATION}"

# Do something with it
echo "*** Blackbox Generator started ***"
echo "  Home directory: $SCRIPT_DIR"

# Generate a list of available configurations
python $SCRIPT_DIR/parse_template.py templates/available_configurations.tmp.template available_configurations.tmp $SCRIPT_DIR/blackbox_config.json --dir $SCRIPT_DIR

# Check if requested configuration exists
if grep -qx "$CONFIGURATION" $SCRIPT_DIR/available_configurations.tmp; then
    echo "Processing configuration: $CONFIGURATION"
else
    echo " *** Configuration not found: $CONFIGURATION - EXITTING!!! ***"
	rm $SCRIPT_DIR/available_configurations.tmp
	exit 1
fi

# Generate the currently used Interbackplane configuration name
python $SCRIPT_DIR/parse_template.py templates/interbackplane_config.tmp.template interbackplane_config.tmp $SCRIPT_DIR/blackbox_config.json --dir $SCRIPT_DIR --config $CONFIGURATION

# Parse Interbackplane templates
python $SCRIPT_DIR/parse_template.py frontend_plugins/interbackplane/templates/frontend_interbackplane.sv.template frontend_plugins/interbackplane/frontend_interbackplane.sv $SCRIPT_DIR/frontend_plugins/interbackplane/interbackplane_config.json --dir $SCRIPT_DIR --config $(<$SCRIPT_DIR/interbackplane_config.tmp)
python $SCRIPT_DIR/parse_template.py frontend_plugins/interbackplane/templates/Manifest.py.fragment.template frontend_plugins/interbackplane/Manifest.py.fragment $SCRIPT_DIR/frontend_plugins/interbackplane/interbackplane_config.json --dir $SCRIPT_DIR --config $(<$SCRIPT_DIR/interbackplane_config.tmp)

# Parse Blackbox templates
python $SCRIPT_DIR/parse_template.py templates/blackbox_config.h.template blackbox_config.h $SCRIPT_DIR/blackbox_config.json --dir $SCRIPT_DIR --config $CONFIGURATION
python $SCRIPT_DIR/parse_template.py templates/blackbox_config.vh.template blackbox_config.vh $SCRIPT_DIR/blackbox_config.json --dir $SCRIPT_DIR --config $CONFIGURATION
python $SCRIPT_DIR/parse_template.py templates/io_blackbox.sv.template io_blackbox.sv $SCRIPT_DIR/blackbox_config.json --dir $SCRIPT_DIR --config $CONFIGURATION
python $SCRIPT_DIR/parse_template.py templates/Manifest.py.template Manifest.py $SCRIPT_DIR/blackbox_config.json --dir $SCRIPT_DIR --config $CONFIGURATION

# Generate VHDL headers
python $SCRIPT_DIR/convert_defines.py $SCRIPT_DIR/blackbox_config
python $SCRIPT_DIR/convert_defines.py $SCRIPT_DIR/blackbox_defines

# Remove temporary files
rm $SCRIPT_DIR/available_configurations.tmp
rm $SCRIPT_DIR/interbackplane_config.tmp

echo " *** Done! *** "