set project_name IFA7;
set esf IFA7 ;#from name.esf
set csf IFA7 ;#from name.csf
cmp add_assignment $project_name    "" |A_A19S                 	 LOCATION   PIN_T17
cmp add_assignment $project_name    "" |A_A17_OUT              	 LOCATION   PIN_N16
cmp add_assignment $project_name    "" |A_A[3]                 	 LOCATION   PIN_C19
cmp add_assignment $project_name    "" |A_A[4]                 	 LOCATION   PIN_D17
cmp add_assignment $project_name    "" |A_A[5]                 	 LOCATION   PIN_F17
cmp add_assignment $project_name    "" |A_A[6]                 	 LOCATION   PIN_G16
cmp add_assignment $project_name    "" |A_A[7]                 	 LOCATION   PIN_G19
cmp add_assignment $project_name    "" |A_A[8]                 	 LOCATION   PIN_G18
cmp add_assignment $project_name    "" |A_A[9]                 	 LOCATION   PIN_H18
cmp add_assignment $project_name    "" |A_A[10]                	 LOCATION   PIN_H20
cmp add_assignment $project_name    "" |A_A[11]                	 LOCATION   PIN_M13
cmp add_assignment $project_name    "" |A_A[12]                	 LOCATION   PIN_M20
cmp add_assignment $project_name    "" |A_A[13]                	 LOCATION   PIN_M17
cmp add_assignment $project_name    "" |A_A[14]                	 LOCATION   PIN_R15
cmp add_assignment $project_name    "" |A_A[15]                	 LOCATION   PIN_P19
cmp add_assignment $project_name    "" |A_A[17]                	 LOCATION   PIN_N19
cmp add_assignment $project_name    "" |A_A[18]                	 LOCATION   PIN_P15
cmp add_assignment $project_name    "" |A_A[19]                	 LOCATION   PIN_J13
cmp add_assignment $project_name    "" |A_A[20]                	 LOCATION   PIN_P16
cmp add_assignment $project_name    "" |A_A[21]                	 LOCATION   PIN_P17
cmp add_assignment $project_name    "" |A_A[22]                	 LOCATION   PIN_T14
cmp add_assignment $project_name    "" |A_A[23]                	 LOCATION   PIN_Y14
cmp add_assignment $project_name    "" |A_A[24]                	 LOCATION   PIN_V14
cmp add_assignment $project_name    "" |A_A[25]                	 LOCATION   PIN_U15
cmp add_assignment $project_name    "" |A_A[26]                	 LOCATION   PIN_W11
cmp add_assignment $project_name    "" |A_A[27]                	 LOCATION   PIN_R11
cmp add_assignment $project_name    "" |A_A[28]                	 LOCATION   PIN_T9
cmp add_assignment $project_name    "" |A_A[29]                	 LOCATION   PIN_Y9
cmp add_assignment $project_name    "" |A_A[30]                	 LOCATION   PIN_T10
cmp add_assignment $project_name    "" |A_A[31]                	 LOCATION   PIN_V10
cmp add_assignment $project_name    "" |A_AC19_OUT             	 LOCATION   PIN_J18
cmp add_assignment $project_name    "" |A_AC26_AC27_OUT        	 LOCATION   PIN_Y10
cmp add_assignment $project_name    "" |A_AC28_AC31_OUT        	 LOCATION   PIN_Y8
cmp add_assignment $project_name    "" |A_AC22_AC25_OUT        	 LOCATION   PIN_U13
cmp add_assignment $project_name    "" |A_B18_B24_OUT          	 LOCATION   PIN_W15
cmp add_assignment $project_name    "" |A_B17_OUT              	 LOCATION   PIN_J20
cmp add_assignment $project_name    "" |A_B[1]                 	 LOCATION   PIN_E19
cmp add_assignment $project_name    "" |A_B[2]                 	 LOCATION   PIN_F16
cmp add_assignment $project_name    "" |A_B[3]                 	 LOCATION   PIN_F19
cmp add_assignment $project_name    "" |A_B[4]                 	 LOCATION   PIN_D19
cmp add_assignment $project_name    "" |A_B[5]                 	 LOCATION   PIN_E17
cmp add_assignment $project_name    "" |A_B[6]                 	 LOCATION   PIN_F20
cmp add_assignment $project_name    "" |A_B[7]                 	 LOCATION   PIN_G20
cmp add_assignment $project_name    "" |A_B[8]                 	 LOCATION   PIN_G14
cmp add_assignment $project_name    "" |A_B[9]                 	 LOCATION   PIN_H16
cmp add_assignment $project_name    "" |A_B[10]                	 LOCATION   PIN_H19
cmp add_assignment $project_name    "" |A_B[11]                	 LOCATION   PIN_J15
cmp add_assignment $project_name    "" |A_B[12]                	 LOCATION   PIN_M19
cmp add_assignment $project_name    "" |A_B[13]                	 LOCATION   PIN_M15
cmp add_assignment $project_name    "" |A_B[14]                	 LOCATION   PIN_P14
cmp add_assignment $project_name    "" |A_B[15]                	 LOCATION   PIN_P20
cmp add_assignment $project_name    "" |A_B[16]                	 LOCATION   PIN_R17
cmp add_assignment $project_name    "" |A_B[17]                	 LOCATION   PIN_J14
cmp add_assignment $project_name    "" |A_B[18]                	 LOCATION   PIN_T16
cmp add_assignment $project_name    "" |A_B[19]                	 LOCATION   PIN_W16
cmp add_assignment $project_name    "" |A_B[20]                	 LOCATION   PIN_V16
cmp add_assignment $project_name    "" |A_B[21]                	 LOCATION   PIN_V17
cmp add_assignment $project_name    "" |A_B[22]                	 LOCATION   PIN_U16
cmp add_assignment $project_name    "" |A_B[23]                	 LOCATION   PIN_Y17
cmp add_assignment $project_name    "" |A_B[24]                	 LOCATION   PIN_W17
cmp add_assignment $project_name    "" |A_B[25]                	 LOCATION   PIN_W12
cmp add_assignment $project_name    "" |A_B[26]                	 LOCATION   PIN_T11
cmp add_assignment $project_name    "" |A_B[27]                	 LOCATION   PIN_T12
cmp add_assignment $project_name    "" |A_B[28]                	 LOCATION   PIN_U12
cmp add_assignment $project_name    "" |A_B[29]                	 LOCATION   PIN_V12
cmp add_assignment $project_name    "" |A_B[30]                	 LOCATION   PIN_T13
cmp add_assignment $project_name    "" |A_B[31]                	 LOCATION   PIN_R13
cmp add_assignment $project_name    "" |A_B[32]                	 LOCATION   PIN_Y13
cmp add_assignment $project_name    "" |A_C20_21_OUT           	 LOCATION   PIN_T18
cmp add_assignment $project_name    "" |A_C19S                 	 LOCATION   PIN_R16
cmp add_assignment $project_name    "" |A_C[1]                 	 LOCATION   PIN_E18
cmp add_assignment $project_name    "" |A_C[3]                 	 LOCATION   PIN_F15
cmp add_assignment $project_name    "" |A_C[4]                 	 LOCATION   PIN_D18
cmp add_assignment $project_name    "" |A_C[5]                 	 LOCATION   PIN_D20
cmp add_assignment $project_name    "" |A_C[6]                 	 LOCATION   PIN_F18
cmp add_assignment $project_name    "" |A_C[7]                 	 LOCATION   PIN_G15
cmp add_assignment $project_name    "" |A_C[8]                 	 LOCATION   PIN_H15
cmp add_assignment $project_name    "" |A_C[9]                 	 LOCATION   PIN_G17
cmp add_assignment $project_name    "" |A_C[10]                	 LOCATION   PIN_H17
cmp add_assignment $project_name    "" |A_C[11]                	 LOCATION   PIN_J16
cmp add_assignment $project_name    "" |A_C[12]                	 LOCATION   PIN_M14
cmp add_assignment $project_name    "" |A_C[13]                	 LOCATION   PIN_M16
cmp add_assignment $project_name    "" |A_C[14]                	 LOCATION   PIN_M18
cmp add_assignment $project_name    "" |A_C[15]                	 LOCATION   PIN_R18
cmp add_assignment $project_name    "" |A_C[17]                	 LOCATION   PIN_R20
cmp add_assignment $project_name    "" |A_C[18]                	 LOCATION   PIN_R19
cmp add_assignment $project_name    "" |A_C[19]                	 LOCATION   PIN_K16
cmp add_assignment $project_name    "" |A_C[20]                	 LOCATION   PIN_U19
cmp add_assignment $project_name    "" |A_C[21]                	 LOCATION   PIN_U18
cmp add_assignment $project_name    "" |A_C[22]                	 LOCATION   PIN_R14
cmp add_assignment $project_name    "" |A_C[23]                	 LOCATION   PIN_W14
cmp add_assignment $project_name    "" |A_C[24]                	 LOCATION   PIN_U14
cmp add_assignment $project_name    "" |A_C[25]                	 LOCATION   PIN_V15
cmp add_assignment $project_name    "" |A_C[26]                	 LOCATION   PIN_U11
cmp add_assignment $project_name    "" |A_C[27]                	 LOCATION   PIN_Y11
cmp add_assignment $project_name    "" |A_C[28]                	 LOCATION   PIN_V9
cmp add_assignment $project_name    "" |A_C[29]                	 LOCATION   PIN_R9
cmp add_assignment $project_name    "" |A_C[30]                	 LOCATION   PIN_W9
cmp add_assignment $project_name    "" |A_C[31]                	 LOCATION   PIN_U10
cmp add_assignment $project_name    "" |A_CLK_20MHZ            	 LOCATION   PIN_K5
cmp add_assignment $project_name    "" |A_CLK_FG               	 LOCATION   PIN_J8
cmp add_assignment $project_name    "" |A_CTRL_LOAD            	 LOCATION   PIN_P5
cmp add_assignment $project_name    "" |A_CTRL_RES             	 LOCATION   PIN_P3
cmp add_assignment $project_name    "" |A_EXT_CLK              	 LOCATION   PIN_K14
cmp add_assignment $project_name    "" |A_INIT_DONE            	 LOCATION   PIN_P7
cmp add_assignment $project_name    "" |A_IO1_OUT              	 LOCATION   PIN_N18
cmp add_assignment $project_name    "" |A_LOADER_CLK           	 LOCATION   PIN_N5
cmp add_assignment $project_name    "" |A_LOADER_DB[0]         	 LOCATION   PIN_R2
cmp add_assignment $project_name    "" |A_LOADER_DB[1]         	 LOCATION   PIN_R6
cmp add_assignment $project_name    "" |A_LOADER_DB[2]         	 LOCATION   PIN_R5
cmp add_assignment $project_name    "" |A_LOADER_DB[3]         	 LOCATION   PIN_R3
cmp add_assignment $project_name    "" |A_LOADER_MISC[0]       	 LOCATION   PIN_T4
cmp add_assignment $project_name    "" |A_LOADER_MISC[1]       	 LOCATION   PIN_T2
cmp add_assignment $project_name    "" |A_LOADER_MISC[2]       	 LOCATION   PIN_T3
cmp add_assignment $project_name    "" |A_LOADER_MISC[3]       	 LOCATION   PIN_U1
cmp add_assignment $project_name    "" |A_LOADER_WRNRD         	 LOCATION   PIN_R1
cmp add_assignment $project_name    "" |A_LOAD_ERROR           	 LOCATION   PIN_P1
cmp add_assignment $project_name    "" |A_LOAD_OK              	 LOCATION   PIN_P2
cmp add_assignment $project_name    "" |A_ME_12MHZ             	 LOCATION   PIN_E8
cmp add_assignment $project_name    "" |A_ME_BOI               	 LOCATION   PIN_C7
cmp add_assignment $project_name    "" |A_ME_BZI               	 LOCATION   PIN_D7
cmp add_assignment $project_name    "" |A_ME_CDS               	 LOCATION   PIN_D5
cmp add_assignment $project_name    "" |A_ME_DSC               	 LOCATION   PIN_B3
cmp add_assignment $project_name    "" |A_ME_EE                	 LOCATION   PIN_A8
cmp add_assignment $project_name    "" |A_ME_ESC               	 LOCATION   PIN_C5
cmp add_assignment $project_name    "" |A_ME_NBOO              	 LOCATION   PIN_C6
cmp add_assignment $project_name    "" |A_ME_NBZO              	 LOCATION   PIN_B6
cmp add_assignment $project_name    "" |A_ME_SD                	 LOCATION   PIN_B5
cmp add_assignment $project_name    "" |A_ME_SDI               	 LOCATION   PIN_B8
cmp add_assignment $project_name    "" |A_ME_SDO               	 LOCATION   PIN_B4
cmp add_assignment $project_name    "" |A_ME_SS                	 LOCATION   PIN_D8
cmp add_assignment $project_name    "" |A_ME_TD                	 LOCATION   PIN_D6
cmp add_assignment $project_name    "" |A_ME_UDI               	 LOCATION   PIN_F8
cmp add_assignment $project_name    "" |A_ME_VW                	 LOCATION   PIN_A4
cmp add_assignment $project_name    "" |A_MIL1_BZI             	 LOCATION   PIN_F7
cmp add_assignment $project_name    "" |A_MIL1_NBZO            	 LOCATION   PIN_N6
cmp add_assignment $project_name    "" |A_MIL1_BOI             	 LOCATION   PIN_A6
cmp add_assignment $project_name    "" |A_MIL1_NBOO            	 LOCATION   PIN_N1
cmp add_assignment $project_name    "" |A_MIL1_NIN_ENA         	 LOCATION   PIN_N4
cmp add_assignment $project_name    "" |A_MIL1_OUT_ENA         	 LOCATION   PIN_N2
cmp add_assignment $project_name    "" |A_NA17_ENA             	 LOCATION   PIN_N20
cmp add_assignment $project_name    "" |A_NAC19_ENA            	 LOCATION   PIN_K15
cmp add_assignment $project_name    "" |A_NAC28_AC31_ENA       	 LOCATION   PIN_U9
cmp add_assignment $project_name    "" |A_NAC22_AC25_ENA       	 LOCATION   PIN_V13
cmp add_assignment $project_name    "" |A_NAC26_AC27_ENA       	 LOCATION   PIN_V11
cmp add_assignment $project_name    "" |A_NB17_ENA             	 LOCATION   PIN_H14
cmp add_assignment $project_name    "" |A_NB18_B24_ENA         	 LOCATION   PIN_T15
cmp add_assignment $project_name    "" |A_NC20_21_ENA          	 LOCATION   PIN_U17
cmp add_assignment $project_name    "" |A_NIO1_ENA             	 LOCATION   PIN_N14
cmp add_assignment $project_name    "" |A_NLED[0]              	 LOCATION   PIN_J5
cmp add_assignment $project_name    "" |A_NLED[1]              	 LOCATION   PIN_J4
cmp add_assignment $project_name    "" |A_NLED[2]              	 LOCATION   PIN_J3
cmp add_assignment $project_name    "" |A_NLED[3]              	 LOCATION   PIN_H6
cmp add_assignment $project_name    "" |A_NLED[4]              	 LOCATION   PIN_H5
cmp add_assignment $project_name    "" |A_NLED[5]              	 LOCATION   PIN_J2
cmp add_assignment $project_name    "" |A_NLED[6]              	 LOCATION   PIN_J1
cmp add_assignment $project_name    "" |A_NLED[7]              	 LOCATION   PIN_H4
cmp add_assignment $project_name    "" |A_NLED[8]              	 LOCATION   PIN_H3
cmp add_assignment $project_name    "" |A_NLED[9]              	 LOCATION   PIN_H2
cmp add_assignment $project_name    "" |A_NLED[10]             	 LOCATION   PIN_H1
cmp add_assignment $project_name    "" |A_NLED[11]             	 LOCATION   PIN_H7
cmp add_assignment $project_name    "" |A_NLED[12]             	 LOCATION   PIN_G4
cmp add_assignment $project_name    "" |A_NLED[13]             	 LOCATION   PIN_G3
cmp add_assignment $project_name    "" |A_NLED[14]             	 LOCATION   PIN_G7
cmp add_assignment $project_name    "" |A_NLED[15]             	 LOCATION   PIN_G6
cmp add_assignment $project_name    "" |A_NLED[16]             	 LOCATION   PIN_G2
cmp add_assignment $project_name    "" |A_NLED[17]             	 LOCATION   PIN_G1
cmp add_assignment $project_name    "" |A_NLED[18]             	 LOCATION   PIN_G5
cmp add_assignment $project_name    "" |A_NLED[19]             	 LOCATION   PIN_F6
cmp add_assignment $project_name    "" |A_NLED[20]             	 LOCATION   PIN_F1
cmp add_assignment $project_name    "" |A_NLED[21]             	 LOCATION   PIN_F2
cmp add_assignment $project_name    "" |A_NLED[22]             	 LOCATION   PIN_F5
cmp add_assignment $project_name    "" |A_NLED_EVT_INR         	 LOCATION   PIN_C3
cmp add_assignment $project_name    "" |A_NLED_EXTCLK          	 LOCATION   PIN_D3
cmp add_assignment $project_name    "" |A_NMANUAL_RES          	 LOCATION   PIN_C2
cmp add_assignment $project_name    "" |A_NOPK_DRDY            	 LOCATION   PIN_M7
cmp add_assignment $project_name    "" |A_NOPK_DRQ             	 LOCATION   PIN_M3
cmp add_assignment $project_name    "" |A_NOPK_INL             	 LOCATION   PIN_M4
cmp add_assignment $project_name    "" |A_NSEL_[6408]          	 LOCATION   PIN_E2
cmp add_assignment $project_name    "" |A_NSWITCH_ENA          	 LOCATION   PIN_C18
cmp add_assignment $project_name    "" |A_P[0]                 	 LOCATION   PIN_B9
cmp add_assignment $project_name    "" |A_P[1]                 	 LOCATION   PIN_A9
cmp add_assignment $project_name    "" |A_P[2]                 	 LOCATION   PIN_D9
cmp add_assignment $project_name    "" |A_P[3]                 	 LOCATION   PIN_C9
cmp add_assignment $project_name    "" |A_P[4]                 	 LOCATION   PIN_E9
cmp add_assignment $project_name    "" |A_P[5]                 	 LOCATION   PIN_E10
cmp add_assignment $project_name    "" |A_P[6]                 	 LOCATION   PIN_B10
cmp add_assignment $project_name    "" |A_P[7]                 	 LOCATION   PIN_A10
cmp add_assignment $project_name    "" |A_P[8]                 	 LOCATION   PIN_F10
cmp add_assignment $project_name    "" |A_P[9]                 	 LOCATION   PIN_C10
cmp add_assignment $project_name    "" |A_P[10]                	 LOCATION   PIN_D10
cmp add_assignment $project_name    "" |A_P[11]                	 LOCATION   PIN_C11
cmp add_assignment $project_name    "" |A_P[12]                	 LOCATION   PIN_D11
cmp add_assignment $project_name    "" |A_P[13]                	 LOCATION   PIN_B11
cmp add_assignment $project_name    "" |A_P[14]                	 LOCATION   PIN_A11
cmp add_assignment $project_name    "" |A_P[15]                	 LOCATION   PIN_E11
cmp add_assignment $project_name    "" |A_P[16]                	 LOCATION   PIN_C12
cmp add_assignment $project_name    "" |A_P[17]                	 LOCATION   PIN_D12
cmp add_assignment $project_name    "" |A_P[18]                	 LOCATION   PIN_B12
cmp add_assignment $project_name    "" |A_P[19]                	 LOCATION   PIN_A12
cmp add_assignment $project_name    "" |A_P[20]                	 LOCATION   PIN_F12
cmp add_assignment $project_name    "" |A_P[21]                	 LOCATION   PIN_E12
cmp add_assignment $project_name    "" |A_P[22]                	 LOCATION   PIN_D13
cmp add_assignment $project_name    "" |A_P[23]                	 LOCATION   PIN_C13
cmp add_assignment $project_name    "" |A_P[24]                	 LOCATION   PIN_B13
cmp add_assignment $project_name    "" |A_P[25]                	 LOCATION   PIN_A13
cmp add_assignment $project_name    "" |A_P[26]                	 LOCATION   PIN_D14
cmp add_assignment $project_name    "" |A_P[27]                	 LOCATION   PIN_C14
cmp add_assignment $project_name    "" |A_P[28]                	 LOCATION   PIN_E13
cmp add_assignment $project_name    "" |A_P[29]                	 LOCATION   PIN_E14
cmp add_assignment $project_name    "" |A_P[30]                	 LOCATION   PIN_B14
cmp add_assignment $project_name    "" |A_P[31]                	 LOCATION   PIN_A14
cmp add_assignment $project_name    "" |A_P[32]                	 LOCATION   PIN_F14
cmp add_assignment $project_name    "" |A_P[33]                	 LOCATION   PIN_E15
cmp add_assignment $project_name    "" |A_P[34]                	 LOCATION   PIN_A15
cmp add_assignment $project_name    "" |A_P[35]                	 LOCATION   PIN_B15
cmp add_assignment $project_name    "" |A_P[36]                	 LOCATION   PIN_D15
cmp add_assignment $project_name    "" |A_P[37]                	 LOCATION   PIN_C15
cmp add_assignment $project_name    "" |A_P[38]                	 LOCATION   PIN_E16
cmp add_assignment $project_name    "" |A_P[39]                	 LOCATION   PIN_D16
cmp add_assignment $project_name    "" |A_P[40]                	 LOCATION   PIN_B16
cmp add_assignment $project_name    "" |A_P[41]                	 LOCATION   PIN_C16
cmp add_assignment $project_name    "" |A_P[42]                	 LOCATION   PIN_A17
cmp add_assignment $project_name    "" |A_P[43]                	 LOCATION   PIN_B17
cmp add_assignment $project_name    "" |A_P[44]                	 LOCATION   PIN_B18
cmp add_assignment $project_name    "" |A_P[45]                	 LOCATION   PIN_C17
cmp add_assignment $project_name    "" |A_RELOAD               	 LOCATION   PIN_P6
cmp add_assignment $project_name    "" |A_SEL_B[0]             	 LOCATION   PIN_U2
cmp add_assignment $project_name    "" |A_SEL_B[1]             	 LOCATION   PIN_U3
cmp add_assignment $project_name    "" |A_SEL_B[2]             	 LOCATION   PIN_V2
cmp add_assignment $project_name    "" |A_SEL_B[3]             	 LOCATION   PIN_V3
cmp add_assignment $project_name    "" |A_TEST[0]              	 LOCATION   PIN_W3
cmp add_assignment $project_name    "" |A_TEST[1]              	 LOCATION   PIN_Y4
cmp add_assignment $project_name    "" |A_TEST[2]              	 LOCATION   PIN_V4
cmp add_assignment $project_name    "" |A_TEST[3]              	 LOCATION   PIN_W4
cmp add_assignment $project_name    "" |A_TEST[4]              	 LOCATION   PIN_T5
cmp add_assignment $project_name    "" |A_TEST[5]              	 LOCATION   PIN_U5
cmp add_assignment $project_name    "" |A_TEST[6]              	 LOCATION   PIN_V5
cmp add_assignment $project_name    "" |A_TEST[7]              	 LOCATION   PIN_W5
cmp add_assignment $project_name    "" |A_TEST[8]              	 LOCATION   PIN_T6
cmp add_assignment $project_name    "" |A_TEST[9]              	 LOCATION   PIN_T7
cmp add_assignment $project_name    "" |A_TEST[10]             	 LOCATION   PIN_W6
cmp add_assignment $project_name    "" |A_TEST[11]             	 LOCATION   PIN_Y6
cmp add_assignment $project_name    "" |A_TEST[12]             	 LOCATION   PIN_U6
cmp add_assignment $project_name    "" |A_TEST[13]             	 LOCATION   PIN_V6
cmp add_assignment $project_name    "" |A_TEST[14]             	 LOCATION   PIN_W7
cmp add_assignment $project_name    "" |A_TEST[15]             	 LOCATION   PIN_Y7
cmp add_assignment $project_name    "" |A_TEST_CLK             	 LOCATION   PIN_E6
cmp add_assignment $project_name    "" |A_TIMING               	 LOCATION   PIN_C4
cmp add_assignment $project_name    "" |A_TP[1]                	 LOCATION   PIN_D1
cmp add_assignment $project_name    "" |A_TP[2]                	 LOCATION   PIN_M1
cmp add_assignment $project_name    "" |A_TP[3]                	 LOCATION   PIN_Y12
cmp add_assignment $project_name    "" |A_TP[4]                	 LOCATION   PIN_Y15
cmp add_assignment $project_name    "" |A_TP[5]                	 LOCATION   PIN_A7
cmp add_assignment $project_name    "" |A_TP[6]                	 LOCATION   PIN_U20
cmp add_assignment $project_name    "" |A_TP[7]                	 LOCATION   PIN_C8
cmp add_assignment $project_name    "" |A_TP[8]                	 LOCATION   PIN_T19
cmp add_assignment $project_name    "" |A_TP[9]                	 LOCATION   PIN_J17
cmp add_assignment $project_name    "" |A_TP[10]               	 LOCATION   PIN_P18
cmp add_assignment $project_name    "" |A_TP[11]               	 LOCATION   PIN_K19
cmp add_assignment $project_name    "" |A_TP[12]               	 LOCATION   PIN_V19
cmp add_assignment $project_name    "" |A_TP[14]               	 LOCATION   PIN_V18
cmp add_assignment $project_name    "" |A_TP[15]               	 LOCATION   PIN_W18
cmp add_assignment $project_name    "" |A_TP[17]               	 LOCATION   PIN_N3
cmp add_assignment $project_name    "" |A_TP[19]               	 LOCATION   PIN_N7
cmp add_assignment $project_name    "" |A_TP[20]               	 LOCATION   PIN_W13
cmp add_assignment $project_name    "" |A_TP[21]               	 LOCATION   PIN_P4
cmp add_assignment $project_name    "" |A_TP[22]               	 LOCATION   PIN_R7
cmp add_assignment $project_name    "" |A_TP[23]               	 LOCATION   PIN_R4
cmp add_assignment $project_name    "" |A_TP[24]               	 LOCATION   PIN_T8
cmp add_assignment $project_name    "" |A_TP[25]               	 LOCATION   PIN_U4
cmp add_assignment $project_name    "" |A_TP[26]               	 LOCATION   PIN_V7
cmp add_assignment $project_name    "" |A_TP[27]               	 LOCATION   PIN_U7
cmp add_assignment $project_name    "" |A_TP[29]               	 LOCATION   PIN_V8
cmp add_assignment $project_name    "" |A_TP[30]               	 LOCATION   PIN_U8
cmp add_assignment $project_name    "" |A_TP[31]               	 LOCATION   PIN_W8
cmp add_assignment $project_name    "" |A_TP[32]               	 LOCATION   PIN_M8
cmp add_assignment $project_name    "" |A_TP[33]               	 LOCATION   PIN_M2
cmp add_assignment $project_name    "" |A_TP[34]               	 LOCATION   PIN_N15
cmp add_assignment $project_name    "" |A_TP[35]               	 LOCATION   PIN_N17
cmp add_assignment $project_name    "" |A_TP[36]               	 LOCATION   PIN_M5
cmp add_assignment $project_name    "" |A_TP[37]               	 LOCATION   PIN_M6
cmp add_assignment $project_name    "" |A_TP[38]               	 LOCATION   PIN_D2
cmp add_assignment $project_name    "" |A_TP[39]               	 LOCATION   PIN_D4
cmp add_assignment $project_name    "" |A_TP[40]               	 LOCATION   PIN_J19
cmp add_assignment $project_name    "" |A_TP[41]               	 LOCATION   PIN_J6
cmp add_assignment $project_name    "" |A_TP[42]               	 LOCATION   PIN_E4
cmp add_assignment $project_name    "" |A_TP[43]               	 LOCATION   PIN_J7
cmp add_assignment $project_name    "" |A_TP[44]               	 LOCATION   PIN_E5
cmp add_assignment $project_name    "" |A_TP[45]               	 LOCATION   PIN_F3
cmp add_assignment $project_name    "" |A_TP[46]               	 LOCATION   PIN_E3
cmp add_assignment $project_name    "" |A_TP[47]               	 LOCATION   PIN_W10
cmp add_assignment $project_name    "" |A_TP[49]               	 LOCATION   PIN_F4
cmp add_assignment $project_name    "" |A_TP[50]               	 LOCATION   PIN_K6
cmp add_assignment $project_name    "" |A_UMIL5V               	 LOCATION   PIN_E7
cmp add_assignment $project_name    "" |A_UMIL15V              	 LOCATION   PIN_B7

	set_global_assignment -name FMAX_REQUIREMENT "20.0 MHz" -section_id F_CLK_20MHz
	set_global_assignment -name DUTY_CYCLE 50 -section_id F_CLK_20MHz

puts "Pinassignment ändern beendet"
