

MIAN_MODULE := oled_test.c

REPOSITORY_DIR := $(shell git rev-parse --show-toplevel)

SOURCE += $(SCU_LIB_SRC_DIR)/display.c


include $(REPOSITORY_DIR)/makefiles/makefile.scu
#=================================== EOF ======================================
