

MIAN_MODULE := oled_test.c


SYN_DIR = ../../../

INCLUDE_DIRS = ./
INCLUDE_DIRS += $(SYN_DIR)top/gsi_scu

SOURCE += $(SYN_DIR)/modules/lm32-include/display.c

TARGET_URL_FILE = ~/target.url

include $(SYN_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================
