

MIAN_MODULE := oled_test.c

SYN_DIR = ../../../

SOURCE += $(SCU_LIB_SRC_DIR)/display.c


include $(SYN_DIR)/modules/lm32_makefiles/makefile.scu
#=================================== EOF ======================================
